/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Element } from '../models/element.js';

/**
 * Creates an instance of Custom
 */
interface Custom {
  /** Array of Elements of validation Errors */
  Elements?: Element[];
  /** Exception number */
  ErrorNumber?: number;
  /** Exception message */
  Message?: string;
  /** Exception type */
  Type?: string;
}

export class CustomError extends ApiError<Custom> {}
