/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { AccountTypeEnum, accountTypeEnumSchema } from './accountTypeEnum.js';
import {
  BankAccountTypeEnum,
  bankAccountTypeEnumSchema,
} from './bankAccountTypeEnum.js';
import { ClassEnum, classEnumSchema } from './classEnum.js';
import {
  CurrencyCodeEnum,
  currencyCodeEnumSchema,
} from './currencyCodeEnum.js';
import { StatusEnum, statusEnumSchema } from './statusEnum.js';
import {
  SystemAccountEnum,
  systemAccountEnumSchema,
} from './systemAccountEnum.js';
import { ValidationError, validationErrorSchema } from './validationError.js';

export interface Account {
  /** The Xero identifier for an account – specified as a string following  the endpoint name   e.g. /297c2dc5-cc47-4afd-8ec8-74990b8761e9 */
  accountID?: string;
  /** Boolean – describes whether the account is shown in the watchlist widget on the dashboard */
  addToWatchlist?: boolean;
  /** For bank accounts only (Account Type BANK) */
  bankAccountNumber?: string;
  /** For bank accounts only. See Bank Account types */
  bankAccountType?: BankAccountTypeEnum;
  /** See Account Class Types */
  mClass?: ClassEnum;
  /** Customer defined alpha numeric account code e.g 200 or SALES (max length = 10) */
  code?: string;
  /** 3 letter alpha code for the currency – see list of currency codes */
  currencyCode?: CurrencyCodeEnum;
  /** Description of the Account. Valid for all types of accounts except bank accounts (max length = 4000) */
  description?: string;
  /** Boolean – describes whether account can have payments applied to it */
  enablePaymentsToAccount?: boolean;
  /** boolean to indicate if an account has an attachment (read only) */
  hasAttachments?: boolean;
  /** Name of account (max length = 150) */
  name?: string;
  /** Shown if set */
  reportingCode?: string;
  /** Shown if set */
  reportingCodeName?: string;
  /** Boolean – describes whether account code is available for use with expense claims */
  showInExpenseClaims?: boolean;
  /** Accounts with a status of ACTIVE can be updated to ARCHIVED. See Account Status Codes */
  status?: StatusEnum;
  /** If this is a system account then this element is returned. See System Account types. Note that non-system accounts may have this element set as either “” or null. */
  systemAccount?: SystemAccountEnum;
  /** The tax type from TaxRates */
  taxType?: string;
  /** See Account Types */
  type?: AccountTypeEnum;
  /** Last modified date UTC format */
  updatedDateUTC?: string;
  /** Displays array of validation error messages from the API */
  validationErrors?: ValidationError[];
}

export const accountSchema: Schema<Account> = lazy(() =>
  object({
    accountID: ['AccountID', optional(string())],
    addToWatchlist: ['AddToWatchlist', optional(boolean())],
    bankAccountNumber: ['BankAccountNumber', optional(string())],
    bankAccountType: ['BankAccountType', optional(bankAccountTypeEnumSchema)],
    mClass: ['Class', optional(classEnumSchema)],
    code: ['Code', optional(string())],
    currencyCode: ['CurrencyCode', optional(currencyCodeEnumSchema)],
    description: ['Description', optional(string())],
    enablePaymentsToAccount: ['EnablePaymentsToAccount', optional(boolean())],
    hasAttachments: ['HasAttachments', optional(boolean())],
    name: ['Name', optional(string())],
    reportingCode: ['ReportingCode', optional(string())],
    reportingCodeName: ['ReportingCodeName', optional(string())],
    showInExpenseClaims: ['ShowInExpenseClaims', optional(boolean())],
    status: ['Status', optional(statusEnumSchema)],
    systemAccount: ['SystemAccount', optional(systemAccountEnumSchema)],
    taxType: ['TaxType', optional(string())],
    type: ['Type', optional(accountTypeEnumSchema)],
    updatedDateUTC: ['UpdatedDateUTC', optional(string())],
    validationErrors: [
      'ValidationErrors',
      optional(array(validationErrorSchema)),
    ],
  })
);
