/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { Account, accountSchema } from './account.js';

export interface Accounts {
  accounts?: Account[];
}

export const accountsSchema: Schema<Accounts> = lazy(() =>
  object({ accounts: ['Accounts', optional(array(accountSchema))] })
);
