/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AccountTypeEnum
 */
export enum AccountTypeEnum {
  BANK = 'BANK',
  CURRENT = 'CURRENT',
  CURRLIAB = 'CURRLIAB',
  DEPRECIATN = 'DEPRECIATN',
  DIRECTCOSTS = 'DIRECTCOSTS',
  EQUITY = 'EQUITY',
  EXPENSE = 'EXPENSE',
  FIXED = 'FIXED',
  INVENTORY = 'INVENTORY',
  LIABILITY = 'LIABILITY',
  NONCURRENT = 'NONCURRENT',
  OTHERINCOME = 'OTHERINCOME',
  OVERHEADS = 'OVERHEADS',
  PREPAYMENT = 'PREPAYMENT',
  REVENUE = 'REVENUE',
  SALES = 'SALES',
  TERMLIAB = 'TERMLIAB',
  PAYGLIABILITY = 'PAYGLIABILITY',
  PAYG = 'PAYG',
  SUPERANNUATIONEXPENSE = 'SUPERANNUATIONEXPENSE',
  SUPERANNUATIONLIABILITY = 'SUPERANNUATIONLIABILITY',
  WAGESEXPENSE = 'WAGESEXPENSE',
}

/**
 * Schema for AccountTypeEnum
 */
export const accountTypeEnumSchema: Schema<AccountTypeEnum> = stringEnum(
  AccountTypeEnum
);
