/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema.js';

export interface AccountsReceivable {
  outstanding?: number;
  overdue?: number;
}

export const accountsReceivableSchema: Schema<AccountsReceivable> = object({
  outstanding: ['Outstanding', optional(number())],
  overdue: ['Overdue', optional(number())],
});
