/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { Action, actionSchema } from './action.js';

export interface Actions {
  actions?: Action[];
}

export const actionsSchema: Schema<Actions> = lazy(() =>
  object({ actions: ['Actions', optional(array(actionSchema))] })
);
