/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import { Status1Enum, status1EnumSchema } from './status1Enum.js';

export interface Action {
  /** Name of the actions for this organisation */
  name?: string;
  /** Status of the action for this organisation */
  status?: Status1Enum;
}

export const actionSchema: Schema<Action> = object({
  name: ['Name', optional(string())],
  status: ['Status', optional(status1EnumSchema)],
});
