/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AddressType1Enum
 */
export enum AddressType1Enum {
  POBOX = 'POBOX',
  STREET = 'STREET',
  DELIVERY = 'DELIVERY',
}

/**
 * Schema for AddressType1Enum
 */
export const addressType1EnumSchema: Schema<AddressType1Enum> = stringEnum(
  AddressType1Enum
);
