/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AddressTypeEnum
 */
export enum AddressTypeEnum {
  POBOX = 'POBOX',
  STREET = 'STREET',
}

/**
 * Schema for AddressTypeEnum
 */
export const addressTypeEnumSchema: Schema<AddressTypeEnum> = stringEnum(
  AddressTypeEnum
);
