/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import { AddressTypeEnum, addressTypeEnumSchema } from './addressTypeEnum.js';

export interface Address {
  /** max length = 500 */
  addressLine1?: string;
  /** max length = 500 */
  addressLine2?: string;
  /** max length = 500 */
  addressLine3?: string;
  /** max length = 500 */
  addressLine4?: string;
  /** define the type of address */
  addressType?: AddressTypeEnum;
  /** max length = 255 */
  attentionTo?: string;
  /** max length = 255 */
  city?: string;
  /** max length = 50, [A-Z], [a-z] only */
  country?: string;
  /** max length = 50 */
  postalCode?: string;
  /** max length = 255 */
  region?: string;
}

export const addressSchema: Schema<Address> = object({
  addressLine1: ['AddressLine1', optional(string())],
  addressLine2: ['AddressLine2', optional(string())],
  addressLine3: ['AddressLine3', optional(string())],
  addressLine4: ['AddressLine4', optional(string())],
  addressType: ['AddressType', optional(addressTypeEnumSchema)],
  attentionTo: ['AttentionTo', optional(string())],
  city: ['City', optional(string())],
  country: ['Country', optional(string())],
  postalCode: ['PostalCode', optional(string())],
  region: ['Region', optional(string())],
});
