/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { CreditNote, creditNoteSchema } from './creditNote.js';
import { Invoice, invoiceSchema } from './invoice.js';
import { Overpayment, overpaymentSchema } from './overpayment.js';
import { Prepayment, prepaymentSchema } from './prepayment.js';
import { ValidationError, validationErrorSchema } from './validationError.js';

export interface Allocation {
  /** the amount being applied to the invoice */
  amount: number;
  creditNote?: CreditNote;
  /** the date the allocation is applied YYYY-MM-DD. */
  date: string;
  invoice: Invoice;
  overpayment?: Overpayment;
  prepayment?: Prepayment;
  /** A string to indicate if a invoice status */
  statusAttributeString?: string;
  /** Displays array of validation error messages from the API */
  validationErrors?: ValidationError[];
}

export const allocationSchema: Schema<Allocation> = lazy(() =>
  object({
    amount: ['Amount', number()],
    creditNote: ['CreditNote', optional(creditNoteSchema)],
    date: ['Date', string()],
    invoice: ['Invoice', invoiceSchema],
    overpayment: ['Overpayment', optional(overpaymentSchema)],
    prepayment: ['Prepayment', optional(prepaymentSchema)],
    statusAttributeString: ['StatusAttributeString', optional(string())],
    validationErrors: [
      'ValidationErrors',
      optional(array(validationErrorSchema)),
    ],
  })
);
