/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { Allocation, allocationSchema } from './allocation.js';

export interface Allocations {
  allocations?: Allocation[];
}

export const allocationsSchema: Schema<Allocations> = lazy(() =>
  object({ allocations: ['Allocations', optional(array(allocationSchema))] })
);
