/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';

export interface Attachment {
  /** Unique ID for the file */
  attachmentID?: string;
  /** Length of the file content */
  contentLength?: number;
  /** Name of the file */
  fileName?: string;
  /** Include the file with the online invoice */
  includeOnline?: boolean;
  /** Type of file */
  mimeType?: string;
  /** URL to the file on xero.com */
  url?: string;
}

export const attachmentSchema: Schema<Attachment> = object({
  attachmentID: ['AttachmentID', optional(string())],
  contentLength: ['ContentLength', optional(number())],
  fileName: ['FileName', optional(string())],
  includeOnline: ['IncludeOnline', optional(boolean())],
  mimeType: ['MimeType', optional(string())],
  url: ['Url', optional(string())],
});
