/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { Attachment, attachmentSchema } from './attachment.js';

export interface Attachments {
  attachments?: Attachment[];
}

export const attachmentsSchema: Schema<Attachments> = lazy(() =>
  object({ attachments: ['Attachments', optional(array(attachmentSchema))] })
);
