/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import { AccountsPayable, accountsPayableSchema } from './accountsPayable.js';
import {
  AccountsReceivable,
  accountsReceivableSchema,
} from './accountsReceivable.js';

/** The raw AccountsReceivable(sales invoices) and AccountsPayable(bills) outstanding and overdue amounts, not converted to base currency (read only) */
export interface Balances {
  accountsPayable?: AccountsPayable;
  accountsReceivable?: AccountsReceivable;
}

export const balancesSchema: Schema<Balances> = lazy(() =>
  object({
    accountsPayable: ['AccountsPayable', optional(accountsPayableSchema)],
    accountsReceivable: [
      'AccountsReceivable',
      optional(accountsReceivableSchema),
    ],
  })
);
