/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema.js';

/** An array to specify multiple currency balances of an account */
export interface BalanceDetails {
  /** The opening balances of the account. Debits are positive, credits are negative values */
  balance?: number;
  /** The currency of the balance (Not required for base currency) */
  currencyCode?: string;
  /** (Optional) Exchange rate to base currency when money is spent or received. If not specified, XE rate for the day is applied */
  currencyRate?: number;
}

export const balanceDetailsSchema: Schema<BalanceDetails> = object({
  balance: ['Balance', optional(number())],
  currencyCode: ['CurrencyCode', optional(string())],
  currencyRate: ['CurrencyRate', optional(number())],
});
