/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { BankTransfer, bankTransferSchema } from './bankTransfer.js';

export interface BankTransfers {
  bankTransfers?: BankTransfer[];
}

export const bankTransfersSchema: Schema<BankTransfers> = lazy(() =>
  object({
    bankTransfers: ['BankTransfers', optional(array(bankTransferSchema))],
  })
);
