/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { Account, accountSchema } from './account.js';
import { Contact, contactSchema } from './contact.js';
import {
  CurrencyCodeEnum,
  currencyCodeEnumSchema,
} from './currencyCodeEnum.js';
import {
  LineAmountTypesEnum,
  lineAmountTypesEnumSchema,
} from './lineAmountTypesEnum.js';
import { LineItem, lineItemSchema } from './lineItem.js';
import { Status8Enum, status8EnumSchema } from './status8Enum.js';
import { Type5Enum, type5EnumSchema } from './type5Enum.js';
import { ValidationError, validationErrorSchema } from './validationError.js';

export interface BankTransaction {
  bankAccount: Account;
  /** Xero generated unique identifier for bank transaction */
  bankTransactionID?: string;
  contact?: Contact;
  /** 3 letter alpha code for the currency – see list of currency codes */
  currencyCode?: CurrencyCodeEnum;
  /** Exchange rate to base currency when money is spent or received. e.g.0.7500 Only used for bank transactions in non base currency. If this isn’t specified for non base currency accounts then either the user-defined rate (preference) or the XE.com day rate will be used. Setting currency is only supported on overpayments. */
  currencyRate?: number;
  /** Date of transaction – YYYY-MM-DD */
  date?: string;
  /** Boolean to indicate if a bank transaction has an attachment */
  hasAttachments?: boolean;
  /** Boolean to show if transaction is reconciled */
  isReconciled?: boolean;
  /** Line amounts are exclusive of tax by default if you don’t specify this element. See Line Amount Types */
  lineAmountTypes?: LineAmountTypesEnum;
  /** See LineItems */
  lineItems: LineItem[];
  /** Xero generated unique identifier for an Overpayment. This will be returned on BankTransactions with a Type of SPEND-OVERPAYMENT or RECEIVE-OVERPAYMENT */
  overpaymentID?: string;
  /** Xero generated unique identifier for a Prepayment. This will be returned on BankTransactions with a Type of SPEND-PREPAYMENT or RECEIVE-PREPAYMENT */
  prepaymentID?: string;
  /** Reference for the transaction. Only supported for SPEND and RECEIVE transactions. */
  reference?: string;
  /** See Bank Transaction Status Codes */
  status?: Status8Enum;
  /** A string to indicate if a invoice status */
  statusAttributeString?: string;
  /** Total of bank transaction excluding taxes */
  subTotal?: number;
  /** Total of bank transaction tax inclusive */
  total?: number;
  /** Total tax on bank transaction */
  totalTax?: number;
  /** See Bank Transaction Types */
  type: Type5Enum;
  /** Last modified date UTC format */
  updatedDateUTC?: string;
  /** URL link to a source document – shown as “Go to App Name” */
  url?: string;
  /** Displays array of validation error messages from the API */
  validationErrors?: ValidationError[];
}

export const bankTransactionSchema: Schema<BankTransaction> = lazy(() =>
  object({
    bankAccount: ['BankAccount', accountSchema],
    bankTransactionID: ['BankTransactionID', optional(string())],
    contact: ['Contact', optional(contactSchema)],
    currencyCode: ['CurrencyCode', optional(currencyCodeEnumSchema)],
    currencyRate: ['CurrencyRate', optional(number())],
    date: ['Date', optional(string())],
    hasAttachments: ['HasAttachments', optional(boolean())],
    isReconciled: ['IsReconciled', optional(boolean())],
    lineAmountTypes: ['LineAmountTypes', optional(lineAmountTypesEnumSchema)],
    lineItems: ['LineItems', array(lineItemSchema)],
    overpaymentID: ['OverpaymentID', optional(string())],
    prepaymentID: ['PrepaymentID', optional(string())],
    reference: ['Reference', optional(string())],
    status: ['Status', optional(status8EnumSchema)],
    statusAttributeString: ['StatusAttributeString', optional(string())],
    subTotal: ['SubTotal', optional(number())],
    total: ['Total', optional(number())],
    totalTax: ['TotalTax', optional(number())],
    type: ['Type', type5EnumSchema],
    updatedDateUTC: ['UpdatedDateUTC', optional(string())],
    url: ['Url', optional(string())],
    validationErrors: [
      'ValidationErrors',
      optional(array(validationErrorSchema)),
    ],
  })
);
