/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { Account, accountSchema } from './account.js';
import { ValidationError, validationErrorSchema } from './validationError.js';

export interface BankTransfer {
  /** amount of the transaction */
  amount: number;
  /** The identifier of the Bank Transfer */
  bankTransferID?: string;
  /** UTC timestamp of creation date of bank transfer */
  createdDateUTC?: string;
  /** The currency rate */
  currencyRate?: number;
  /** The date of the Transfer YYYY-MM-DD */
  date?: string;
  fromBankAccount: Account;
  /** The Bank Transaction ID for the source account */
  fromBankTransactionID?: string;
  /** Boolean to indicate if a Bank Transfer has an attachment */
  hasAttachments?: boolean;
  toBankAccount: Account;
  /** The Bank Transaction ID for the destination account */
  toBankTransactionID?: string;
  /** Displays array of validation error messages from the API */
  validationErrors?: ValidationError[];
}

export const bankTransferSchema: Schema<BankTransfer> = lazy(() =>
  object({
    amount: ['Amount', number()],
    bankTransferID: ['BankTransferID', optional(string())],
    createdDateUTC: ['CreatedDateUTC', optional(string())],
    currencyRate: ['CurrencyRate', optional(number())],
    date: ['Date', optional(string())],
    fromBankAccount: ['FromBankAccount', accountSchema],
    fromBankTransactionID: ['FromBankTransactionID', optional(string())],
    hasAttachments: ['HasAttachments', optional(boolean())],
    toBankAccount: ['ToBankAccount', accountSchema],
    toBankTransactionID: ['ToBankTransactionID', optional(string())],
    validationErrors: [
      'ValidationErrors',
      optional(array(validationErrorSchema)),
    ],
  })
);
