/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for BankAccountTypeEnum
 */
export enum BankAccountTypeEnum {
  BANK = 'BANK',
  CREDITCARD = 'CREDITCARD',
  PAYPAL = 'PAYPAL',
  NONE = 'NONE',
}

/**
 * Schema for BankAccountTypeEnum
 */
export const bankAccountTypeEnumSchema: Schema<BankAccountTypeEnum> = stringEnum(
  BankAccountTypeEnum
);
