/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { BankTransaction, bankTransactionSchema } from './bankTransaction.js';

export interface BankTransactions {
  bankTransactions?: BankTransaction[];
}

export const bankTransactionsSchema: Schema<BankTransactions> = lazy(() =>
  object({
    bankTransactions: [
      'BankTransactions',
      optional(array(bankTransactionSchema)),
    ],
  })
);
