/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { BatchPayment, batchPaymentSchema } from './batchPayment.js';

export interface BatchPayments {
  batchPayments?: BatchPayment[];
}

export const batchPaymentsSchema: Schema<BatchPayments> = lazy(() =>
  object({
    batchPayments: ['BatchPayments', optional(array(batchPaymentSchema))],
  })
);
