/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Bank details for use on a batch payment stored with each contact */
export interface BatchPaymentDetails {
  /** Name of bank for use with Batch Payments */
  bankAccountName?: string;
  /** Bank account number for use with Batch Payments */
  bankAccountNumber?: string;
  /** (NZ Only) Optional references for the batch payment transaction. It will also show with the batch payment transaction in the bank reconciliation Find & Match screen. Depending on your individual bank, the detail may also show on the bank statement you import into Xero. */
  code?: string;
  /** (Non-NZ Only) These details are sent to the org’s bank as a reference for the batch payment transaction. They will also show with the batch payment transaction in the bank reconciliation Find & Match screen. Depending on your individual bank, the detail may also show on the bank statement imported into Xero. Maximum field length = 18 */
  details?: string;
  /** (NZ Only) Optional references for the batch payment transaction. It will also show with the batch payment transaction in the bank reconciliation Find & Match screen. Depending on your individual bank, the detail may also show on the bank statement you import into Xero. */
  reference?: string;
}

export const batchPaymentDetailsSchema: Schema<BatchPaymentDetails> = object({
  bankAccountName: ['BankAccountName', optional(string())],
  bankAccountNumber: ['BankAccountNumber', optional(string())],
  code: ['Code', optional(string())],
  details: ['Details', optional(string())],
  reference: ['Reference', optional(string())],
});
