/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { Account, accountSchema } from './account.js';
import { Payment, paymentSchema } from './payment.js';
import { Status9Enum, status9EnumSchema } from './status9Enum.js';
import { Type6Enum, type6EnumSchema } from './type6Enum.js';

export interface BatchPayment {
  account?: Account;
  /** The amount of the payment. Must be less than or equal to the outstanding amount owing on the invoice e.g. 200.00 */
  amount?: number;
  /** The Xero generated unique identifier for the bank transaction (read-only) */
  batchPaymentID?: string;
  /** (NZ Only) Optional references for the batch payment transaction. It will also show with the batch payment transaction in the bank reconciliation Find & Match screen. Depending on your individual bank, the detail may also show on the bank statement you import into Xero. */
  code?: string;
  /** Date the payment is being made (YYYY-MM-DD) e.g. 2009-09-06 */
  date?: string;
  /** Date the payment is being made (YYYY-MM-DD) e.g. 2009-09-06 */
  dateString?: string;
  /** (Non-NZ Only) These details are sent to the org’s bank as a reference for the batch payment transaction. They will also show with the batch payment transaction in the bank reconciliation Find & Match screen. Depending on your individual bank, the detail may also show on the bank statement imported into Xero. Maximum field length = 18 */
  details?: string;
  /** Booelan that tells you if the batch payment has been reconciled (read-only) */
  isReconciled?: string;
  /** (UK Only) Only shows on the statement line in Xero. Max length =18 */
  narrative?: string;
  /** (NZ Only) Optional references for the batch payment transaction. It will also show with the batch payment transaction in the bank reconciliation Find & Match screen. Depending on your individual bank, the detail may also show on the bank statement you import into Xero. */
  particulars?: string;
  /** An array of payments */
  payments?: Payment[];
  /** (NZ Only) Optional references for the batch payment transaction. It will also show with the batch payment transaction in the bank reconciliation Find & Match screen. Depending on your individual bank, the detail may also show on the bank statement you import into Xero. */
  reference?: string;
  /** AUTHORISED or DELETED (read-only). New batch payments will have a status of AUTHORISED. It is not possible to delete batch payments via the API. */
  status?: Status9Enum;
  /** The total of the payments that make up the batch (read-only) */
  totalAmount?: string;
  /** PAYBATCH for bill payments or RECBATCH for sales invoice payments (read-only) */
  type?: Type6Enum;
  /** UTC timestamp of last update to the payment */
  updatedDateUTC?: string;
}

export const batchPaymentSchema: Schema<BatchPayment> = lazy(() =>
  object({
    account: ['Account', optional(accountSchema)],
    amount: ['Amount', optional(number())],
    batchPaymentID: ['BatchPaymentID', optional(string())],
    code: ['Code', optional(string())],
    date: ['Date', optional(string())],
    dateString: ['DateString', optional(string())],
    details: ['Details', optional(string())],
    isReconciled: ['IsReconciled', optional(string())],
    narrative: ['Narrative', optional(string())],
    particulars: ['Particulars', optional(string())],
    payments: ['Payments', optional(array(paymentSchema))],
    reference: ['Reference', optional(string())],
    status: ['Status', optional(status9EnumSchema)],
    totalAmount: ['TotalAmount', optional(string())],
    type: ['Type', optional(type6EnumSchema)],
    updatedDateUTC: ['UpdatedDateUTC', optional(string())],
  })
);
