/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema.js';
import {
  PaymentTermTypeEnum,
  paymentTermTypeEnumSchema,
} from './paymentTermTypeEnum.js';

export interface Bill {
  /** Day of Month (0-31) */
  day?: number;
  type?: PaymentTermTypeEnum;
}

export const billSchema: Schema<Bill> = object({
  day: ['Day', optional(number())],
  type: ['Type', optional(paymentTermTypeEnumSchema)],
});
