/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema.js';
import { TypeEnum, typeEnumSchema } from './typeEnum.js';

export interface BrandingTheme {
  /** Xero identifier */
  brandingThemeID?: string;
  /** UTC timestamp of creation date of branding theme */
  createdDateUTC?: string;
  /** The location of the image file used as the logo on this branding theme */
  logoUrl?: string;
  /** Name of branding theme */
  name?: string;
  /** Integer – ranked order of branding theme. The default branding theme has a value of 0 */
  sortOrder?: number;
  /** Always INVOICE */
  type?: TypeEnum;
}

export const brandingThemeSchema: Schema<BrandingTheme> = object({
  brandingThemeID: ['BrandingThemeID', optional(string())],
  createdDateUTC: ['CreatedDateUTC', optional(string())],
  logoUrl: ['LogoUrl', optional(string())],
  name: ['Name', optional(string())],
  sortOrder: ['SortOrder', optional(number())],
  type: ['Type', optional(typeEnumSchema)],
});
