/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { BrandingTheme, brandingThemeSchema } from './brandingTheme.js';

export interface BrandingThemes {
  brandingThemes?: BrandingTheme[];
}

export const brandingThemesSchema: Schema<BrandingThemes> = lazy(() =>
  object({
    brandingThemes: ['BrandingThemes', optional(array(brandingThemeSchema))],
  })
);
