/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, optional, Schema } from '../schema.js';

export interface CISOrgSetting {
  /** true or false - Boolean that describes if the organisation is a CIS Contractor */
  cISContractorEnabled?: boolean;
  /** true or false - Boolean that describes if the organisation is a CIS SubContractor */
  cISSubContractorEnabled?: boolean;
  /** CIS Deduction rate for the organisation */
  rate?: number;
}

export const cISOrgSettingSchema: Schema<CISOrgSetting> = object({
  cISContractorEnabled: ['CISContractorEnabled', optional(boolean())],
  cISSubContractorEnabled: ['CISSubContractorEnabled', optional(boolean())],
  rate: ['Rate', optional(number())],
});
