/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { CISOrgSetting, cISOrgSettingSchema } from './cISOrgSetting.js';

export interface CISOrgSettings {
  cISSettings?: CISOrgSetting[];
}

export const cISOrgSettingsSchema: Schema<CISOrgSettings> = lazy(() =>
  object({ cISSettings: ['CISSettings', optional(array(cISOrgSettingSchema))] })
);
