/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, optional, Schema } from '../schema.js';

export interface CISSetting {
  /** Boolean that describes if the contact is a CIS Subcontractor */
  cISEnabled?: boolean;
  /** CIS Deduction rate for the contact if he is a subcontractor. If the contact is not CISEnabled, then the rate is not returned */
  rate?: number;
}

export const cISSettingSchema: Schema<CISSetting> = object({
  cISEnabled: ['CISEnabled', optional(boolean())],
  rate: ['Rate', optional(number())],
});
