/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { CISSetting, cISSettingSchema } from './cISSetting.js';

export interface CISSettings {
  cISSettings?: CISSetting[];
}

export const cISSettingsSchema: Schema<CISSettings> = lazy(() =>
  object({ cISSettings: ['CISSettings', optional(array(cISSettingSchema))] })
);
