/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ClassEnum
 */
export enum ClassEnum {
  ASSET = 'ASSET',
  EQUITY = 'EQUITY',
  EXPENSE = 'EXPENSE',
  LIABILITY = 'LIABILITY',
  REVENUE = 'REVENUE',
}

/**
 * Schema for ClassEnum
 */
export const classEnumSchema: Schema<ClassEnum> = stringEnum(ClassEnum);
