/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Class1Enum
 */
export enum Class1Enum {
  DEMO = 'DEMO',
  TRIAL = 'TRIAL',
  STARTER = 'STARTER',
  STANDARD = 'STANDARD',
  PREMIUM = 'PREMIUM',
  PREMIUM20 = 'PREMIUM_20',
  PREMIUM50 = 'PREMIUM_50',
  PREMIUM100 = 'PREMIUM_100',
  LEDGER = 'LEDGER',
  GSTCASHBOOK = 'GST_CASHBOOK',
  NONGSTCASHBOOK = 'NON_GST_CASHBOOK',
}

/**
 * Schema for Class1Enum
 */
export const class1EnumSchema: Schema<Class1Enum> = stringEnum(Class1Enum);
