/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { Contact, contactSchema } from './contact.js';

export interface Contacts {
  contacts?: Contact[];
}

export const contactsSchema: Schema<Contacts> = lazy(() =>
  object({ contacts: ['Contacts', optional(array(contactSchema))] })
);
