/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ContactStatusEnum
 */
export enum ContactStatusEnum {
  ACTIVE = 'ACTIVE',
  ARCHIVED = 'ARCHIVED',
  GDPRREQUEST = 'GDPRREQUEST',
}

/**
 * Schema for ContactStatusEnum
 */
export const contactStatusEnumSchema: Schema<ContactStatusEnum> = stringEnum(
  ContactStatusEnum
);
