/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { ContactGroup, contactGroupSchema } from './contactGroup.js';

export interface ContactGroups {
  contactGroups?: ContactGroup[];
}

export const contactGroupsSchema: Schema<ContactGroups> = lazy(() =>
  object({
    contactGroups: ['ContactGroups', optional(array(contactGroupSchema))],
  })
);
