/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema.js';

export interface ContactPerson {
  /** Email address of person */
  emailAddress?: string;
  /** First name of person */
  firstName?: string;
  /** boolean to indicate whether contact should be included on emails with invoices etc. */
  includeInEmails?: boolean;
  /** Last name of person */
  lastName?: string;
}

export const contactPersonSchema: Schema<ContactPerson> = object({
  emailAddress: ['EmailAddress', optional(string())],
  firstName: ['FirstName', optional(string())],
  includeInEmails: ['IncludeInEmails', optional(boolean())],
  lastName: ['LastName', optional(string())],
});
