/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { Address, addressSchema } from './address.js';
import { Attachment, attachmentSchema } from './attachment.js';
import { Balances, balancesSchema } from './balances.js';
import {
  BatchPaymentDetails,
  batchPaymentDetailsSchema,
} from './batchPaymentDetails.js';
import { BrandingTheme, brandingThemeSchema } from './brandingTheme.js';
import { ContactGroup, contactGroupSchema } from './contactGroup.js';
import { ContactPerson, contactPersonSchema } from './contactPerson.js';
import {
  ContactStatusEnum,
  contactStatusEnumSchema,
} from './contactStatusEnum.js';
import {
  CurrencyCodeEnum,
  currencyCodeEnumSchema,
} from './currencyCodeEnum.js';
import { PaymentTerm, paymentTermSchema } from './paymentTerm.js';
import { Phone, phoneSchema } from './phone.js';
import {
  SalesTrackingCategory,
  salesTrackingCategorySchema,
} from './salesTrackingCategory.js';
import { ValidationError, validationErrorSchema } from './validationError.js';

export interface Contact {
  /** A user defined account number. This can be updated via the API and the Xero UI (max length = 50) */
  accountNumber?: string;
  /** The tax type from TaxRates */
  accountsPayableTaxType?: string;
  /** The tax type from TaxRates */
  accountsReceivableTaxType?: string;
  /** Store certain address types for a contact – see address types */
  addresses?: Address[];
  /** Displays array of attachments from the API */
  attachments?: Attachment[];
  /** The raw AccountsReceivable(sales invoices) and AccountsPayable(bills) outstanding and overdue amounts, not converted to base currency (read only) */
  balances?: Balances;
  /** Bank account number of contact */
  bankAccountDetails?: string;
  /** Bank details for use on a batch payment stored with each contact */
  batchPayments?: BatchPaymentDetails;
  brandingTheme?: BrandingTheme;
  /** Displays which contact groups a contact is included in */
  contactGroups?: ContactGroup[];
  /** Xero identifier */
  contactID?: string;
  /** This can be updated via the API only i.e. This field is read only on the Xero contact screen, used to identify contacts in external systems (max length = 50). If the Contact Number is used, this is displayed as Contact Code in the Contacts UI in Xero. */
  contactNumber?: string;
  /** See contact persons */
  contactPersons?: ContactPerson[];
  /** Current status of a contact – see contact status types */
  contactStatus?: ContactStatusEnum;
  /** 3 letter alpha code for the currency – see list of currency codes */
  defaultCurrency?: CurrencyCodeEnum;
  /** The default discount rate for the contact (read only) */
  discount?: number;
  /** Email address of contact person (umlauts not supported) (max length  = 255) */
  emailAddress?: string;
  /** First name of contact person (max length = 255) */
  firstName?: string;
  /** A boolean to indicate if a contact has an attachment */
  hasAttachments?: boolean;
  /** A boolean to indicate if a contact has an validation errors */
  hasValidationErrors?: boolean;
  /** true or false – Boolean that describes if a contact has any AR invoices entered against them. Cannot be set via PUT or POST – it is automatically set when an accounts receivable invoice is generated against this contact. */
  isCustomer?: boolean;
  /** true or false – Boolean that describes if a contact that has any AP  invoices entered against them. Cannot be set via PUT or POST – it is automatically set when an accounts payable invoice is generated against this contact. */
  isSupplier?: boolean;
  /** Last name of contact person (max length = 255) */
  lastName?: string;
  /** Full name of contact/organisation (max length = 255) */
  name?: string;
  paymentTerms?: PaymentTerm;
  /** Store certain phone types for a contact – see phone types */
  phones?: Phone[];
  /** The default purchases account code for contacts */
  purchasesDefaultAccountCode?: string;
  /** The default purchases tracking categories for contacts */
  purchasesTrackingCategories?: SalesTrackingCategory[];
  /** The default sales account code for contacts */
  salesDefaultAccountCode?: string;
  /** The default sales tracking categories for contacts */
  salesTrackingCategories?: SalesTrackingCategory[];
  /** Skype user name of contact */
  skypeUserName?: string;
  /** Status of object */
  statusAttributeString?: string;
  /** Tax number of contact – this is also known as the ABN (Australia), GST Number (New Zealand), VAT Number (UK) or Tax ID Number (US and global) in the Xero UI depending on which regionalized version of Xero you are using (max length = 50) */
  taxNumber?: string;
  /** The name of the Tracking Category assigned to the contact under SalesTrackingCategories and PurchasesTrackingCategories */
  trackingCategoryName?: string;
  /** The name of the Tracking Option assigned to the contact under SalesTrackingCategories and PurchasesTrackingCategories */
  trackingCategoryOption?: string;
  /** UTC timestamp of last update to contact */
  updatedDateUTC?: string;
  /** Displays validation errors returned from the API */
  validationErrors?: ValidationError[];
  /** Website address for contact (read only) */
  website?: string;
  /** Store XeroNetworkKey for contacts. */
  xeroNetworkKey?: string;
}

export const contactSchema: Schema<Contact> = lazy(() =>
  object({
    accountNumber: ['AccountNumber', optional(string())],
    accountsPayableTaxType: ['AccountsPayableTaxType', optional(string())],
    accountsReceivableTaxType: [
      'AccountsReceivableTaxType',
      optional(string()),
    ],
    addresses: ['Addresses', optional(array(addressSchema))],
    attachments: ['Attachments', optional(array(attachmentSchema))],
    balances: ['Balances', optional(balancesSchema)],
    bankAccountDetails: ['BankAccountDetails', optional(string())],
    batchPayments: ['BatchPayments', optional(batchPaymentDetailsSchema)],
    brandingTheme: ['BrandingTheme', optional(brandingThemeSchema)],
    contactGroups: ['ContactGroups', optional(array(contactGroupSchema))],
    contactID: ['ContactID', optional(string())],
    contactNumber: ['ContactNumber', optional(string())],
    contactPersons: ['ContactPersons', optional(array(contactPersonSchema))],
    contactStatus: ['ContactStatus', optional(contactStatusEnumSchema)],
    defaultCurrency: ['DefaultCurrency', optional(currencyCodeEnumSchema)],
    discount: ['Discount', optional(number())],
    emailAddress: ['EmailAddress', optional(string())],
    firstName: ['FirstName', optional(string())],
    hasAttachments: ['HasAttachments', optional(boolean())],
    hasValidationErrors: ['HasValidationErrors', optional(boolean())],
    isCustomer: ['IsCustomer', optional(boolean())],
    isSupplier: ['IsSupplier', optional(boolean())],
    lastName: ['LastName', optional(string())],
    name: ['Name', optional(string())],
    paymentTerms: ['PaymentTerms', optional(paymentTermSchema)],
    phones: ['Phones', optional(array(phoneSchema))],
    purchasesDefaultAccountCode: [
      'PurchasesDefaultAccountCode',
      optional(string()),
    ],
    purchasesTrackingCategories: [
      'PurchasesTrackingCategories',
      optional(array(salesTrackingCategorySchema)),
    ],
    salesDefaultAccountCode: ['SalesDefaultAccountCode', optional(string())],
    salesTrackingCategories: [
      'SalesTrackingCategories',
      optional(array(salesTrackingCategorySchema)),
    ],
    skypeUserName: ['SkypeUserName', optional(string())],
    statusAttributeString: ['StatusAttributeString', optional(string())],
    taxNumber: ['TaxNumber', optional(string())],
    trackingCategoryName: ['TrackingCategoryName', optional(string())],
    trackingCategoryOption: ['TrackingCategoryOption', optional(string())],
    updatedDateUTC: ['UpdatedDateUTC', optional(string())],
    validationErrors: [
      'ValidationErrors',
      optional(array(validationErrorSchema)),
    ],
    website: ['Website', optional(string())],
    xeroNetworkKey: ['XeroNetworkKey', optional(string())],
  })
);
