/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import { Contact, contactSchema } from './contact.js';
import { Status2Enum, status2EnumSchema } from './status2Enum.js';

export interface ContactGroup {
  /** The Xero identifier for an contact group – specified as a string following the endpoint name. e.g. /297c2dc5-cc47-4afd-8ec8-74990b8761e9 */
  contactGroupID?: string;
  /** The ContactID and Name of Contacts in a contact group. Returned on GETs when the ContactGroupID is supplied in the URL. */
  contacts?: Contact[];
  /** The Name of the contact group. Required when creating a new contact  group */
  name?: string;
  /** The Status of a contact group. To delete a contact group update the status to DELETED. Only contact groups with a status of ACTIVE are returned on GETs. */
  status?: Status2Enum;
}

export const contactGroupSchema: Schema<ContactGroup> = lazy(() =>
  object({
    contactGroupID: ['ContactGroupID', optional(string())],
    contacts: ['Contacts', optional(array(contactSchema))],
    name: ['Name', optional(string())],
    status: ['Status', optional(status2EnumSchema)],
  })
);
