/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema.js';

/** The date when the organisation starts using Xero */
export interface ConversionDate {
  /** The month the organisation starts using Xero. Value is an integer between 1 and 12 */
  month?: number;
  /** The year the organisation starts using Xero. Value is an integer greater than 2006 */
  year?: number;
}

export const conversionDateSchema: Schema<ConversionDate> = object({
  month: ['Month', optional(number())],
  year: ['Year', optional(number())],
});
