/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { BalanceDetails, balanceDetailsSchema } from './balanceDetails.js';

/** Balance supplied for each account that has a value as at the conversion date. */
export interface ConversionBalances {
  /** The account code for a account */
  accountCode?: string;
  /** The opening balances of the account. Debits are positive, credits are negative values */
  balance?: number;
  balanceDetails?: BalanceDetails[];
}

export const conversionBalancesSchema: Schema<ConversionBalances> = lazy(() =>
  object({
    accountCode: ['AccountCode', optional(string())],
    balance: ['Balance', optional(number())],
    balanceDetails: ['BalanceDetails', optional(array(balanceDetailsSchema))],
  })
);
