/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { CreditNote, creditNoteSchema } from './creditNote.js';

export interface CreditNotes {
  creditNotes?: CreditNote[];
}

export const creditNotesSchema: Schema<CreditNotes> = lazy(() =>
  object({ creditNotes: ['CreditNotes', optional(array(creditNoteSchema))] })
);
