/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { Allocation, allocationSchema } from './allocation.js';
import { Contact, contactSchema } from './contact.js';
import {
  CurrencyCodeEnum,
  currencyCodeEnumSchema,
} from './currencyCodeEnum.js';
import {
  LineAmountTypesEnum,
  lineAmountTypesEnumSchema,
} from './lineAmountTypesEnum.js';
import { LineItem, lineItemSchema } from './lineItem.js';
import { Payment, paymentSchema } from './payment.js';
import { Status7Enum, status7EnumSchema } from './status7Enum.js';
import { Type4Enum, type4EnumSchema } from './type4Enum.js';
import { ValidationError, validationErrorSchema } from './validationError.js';

export interface CreditNote {
  /** See Allocations */
  allocations?: Allocation[];
  /** The amount of applied to an invoice */
  appliedAmount?: number;
  /** See BrandingThemes */
  brandingThemeID?: string;
  /** CIS deduction for UK contractors */
  cISDeduction?: number;
  /** CIS Deduction rate for the organisation */
  cISRate?: number;
  contact?: Contact;
  /** Xero generated unique identifier */
  creditNoteID?: string;
  /** ACCRECCREDIT – Unique alpha numeric code identifying credit note (when missing will auto-generate from your Organisation Invoice Settings) */
  creditNoteNumber?: string;
  /** 3 letter alpha code for the currency – see list of currency codes */
  currencyCode?: CurrencyCodeEnum;
  /** The currency rate for a multicurrency invoice. If no rate is specified, the XE.com day rate is used */
  currencyRate?: number;
  /** The date the credit note is issued YYYY-MM-DD. If the Date element is not specified then it will default to the current date based on the timezone setting of the organisation */
  date?: string;
  /** Date invoice is due – YYYY-MM-DD */
  dueDate?: string;
  /** Date when credit note was fully paid(UTC format) */
  fullyPaidOnDate?: string;
  /** boolean to indicate if a credit note has an attachment */
  hasAttachments?: boolean;
  /** A boolean to indicate if a credit note has an validation errors */
  hasErrors?: boolean;
  /** Line amounts are exclusive of tax by default if you don’t specify this element. See Line Amount Types */
  lineAmountTypes?: LineAmountTypesEnum;
  /** See Invoice Line Items */
  lineItems?: LineItem[];
  /** See Payments */
  payments?: Payment[];
  /** ACCRECCREDIT only – additional reference number */
  reference?: string;
  /** The remaining credit balance on the Credit Note */
  remainingCredit?: number;
  /** boolean to indicate if a credit note has been sent to a contact via  the Xero app (currently read only) */
  sentToContact?: boolean;
  /** See Credit Note Status Codes */
  status?: Status7Enum;
  /** A string to indicate if a invoice status */
  statusAttributeString?: string;
  /** The subtotal of the credit note excluding taxes */
  subTotal?: number;
  /** The total of the Credit Note(subtotal + total tax) */
  total?: number;
  /** The total tax on the credit note */
  totalTax?: number;
  /** See Credit Note Types */
  type?: Type4Enum;
  /** UTC timestamp of last update to the credit note */
  updatedDateUTC?: string;
  /** Displays array of validation error messages from the API */
  validationErrors?: ValidationError[];
  /** Displays array of warning messages from the API */
  warnings?: ValidationError[];
}

export const creditNoteSchema: Schema<CreditNote> = lazy(() =>
  object({
    allocations: ['Allocations', optional(array(allocationSchema))],
    appliedAmount: ['AppliedAmount', optional(number())],
    brandingThemeID: ['BrandingThemeID', optional(string())],
    cISDeduction: ['CISDeduction', optional(number())],
    cISRate: ['CISRate', optional(number())],
    contact: ['Contact', optional(contactSchema)],
    creditNoteID: ['CreditNoteID', optional(string())],
    creditNoteNumber: ['CreditNoteNumber', optional(string())],
    currencyCode: ['CurrencyCode', optional(currencyCodeEnumSchema)],
    currencyRate: ['CurrencyRate', optional(number())],
    date: ['Date', optional(string())],
    dueDate: ['DueDate', optional(string())],
    fullyPaidOnDate: ['FullyPaidOnDate', optional(string())],
    hasAttachments: ['HasAttachments', optional(boolean())],
    hasErrors: ['HasErrors', optional(boolean())],
    lineAmountTypes: ['LineAmountTypes', optional(lineAmountTypesEnumSchema)],
    lineItems: ['LineItems', optional(array(lineItemSchema))],
    payments: ['Payments', optional(array(paymentSchema))],
    reference: ['Reference', optional(string())],
    remainingCredit: ['RemainingCredit', optional(number())],
    sentToContact: ['SentToContact', optional(boolean())],
    status: ['Status', optional(status7EnumSchema)],
    statusAttributeString: ['StatusAttributeString', optional(string())],
    subTotal: ['SubTotal', optional(number())],
    total: ['Total', optional(number())],
    totalTax: ['TotalTax', optional(number())],
    type: ['Type', optional(type4EnumSchema)],
    updatedDateUTC: ['UpdatedDateUTC', optional(string())],
    validationErrors: [
      'ValidationErrors',
      optional(array(validationErrorSchema)),
    ],
    warnings: ['Warnings', optional(array(validationErrorSchema))],
  })
);
