/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { Currency, currencySchema } from './currency.js';

export interface Currencies {
  currencies?: Currency[];
}

export const currenciesSchema: Schema<Currencies> = lazy(() =>
  object({ currencies: ['Currencies', optional(array(currencySchema))] })
);
