/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import {
  CurrencyCodeEnum,
  currencyCodeEnumSchema,
} from './currencyCodeEnum.js';

export interface Currency {
  /** 3 letter alpha code for the currency – see list of currency codes */
  code?: CurrencyCodeEnum;
  /** Name of Currency */
  description?: string;
}

export const currencySchema: Schema<Currency> = object({
  code: ['Code', optional(currencyCodeEnumSchema)],
  description: ['Description', optional(string())],
});
