/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for DueDateTypeEnum
 */
export enum DueDateTypeEnum {
  DAYSAFTERBILLDATE = 'DAYSAFTERBILLDATE',
  DAYSAFTERBILLMONTH = 'DAYSAFTERBILLMONTH',
  DAYSAFTERINVOICEDATE = 'DAYSAFTERINVOICEDATE',
  DAYSAFTERINVOICEMONTH = 'DAYSAFTERINVOICEMONTH',
  OFCURRENTMONTH = 'OFCURRENTMONTH',
  OFFOLLOWINGMONTH = 'OFFOLLOWINGMONTH',
}

/**
 * Schema for DueDateTypeEnum
 */
export const dueDateTypeEnumSchema: Schema<DueDateTypeEnum> = stringEnum(
  DueDateTypeEnum
);
