/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for EditionEnum
 */
export enum EditionEnum {
  BUSINESS = 'BUSINESS',
  PARTNER = 'PARTNER',
}

/**
 * Schema for EditionEnum
 */
export const editionEnumSchema: Schema<EditionEnum> = stringEnum(EditionEnum);
