/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import { ValidationError, validationErrorSchema } from './validationError.js';

export interface Element {
  bankTransactionID?: string;
  /** Unique ID for batch payment object with validation error */
  batchPaymentID?: string;
  contactID?: string;
  creditNoteID?: string;
  invoiceID?: string;
  itemID?: string;
  purchaseOrderID?: string;
  /** Array of Validation Error message */
  validationErrors?: ValidationError[];
}

export const elementSchema: Schema<Element> = lazy(() =>
  object({
    bankTransactionID: ['BankTransactionID', optional(string())],
    batchPaymentID: ['BatchPaymentID', optional(string())],
    contactID: ['ContactID', optional(string())],
    creditNoteID: ['CreditNoteID', optional(string())],
    invoiceID: ['InvoiceID', optional(string())],
    itemID: ['ItemID', optional(string())],
    purchaseOrderID: ['PurchaseOrderID', optional(string())],
    validationErrors: [
      'ValidationErrors',
      optional(array(validationErrorSchema)),
    ],
  })
);
