/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import { ExternalLink, externalLinkSchema } from './externalLink.js';
import { Status10Enum, status10EnumSchema } from './status10Enum.js';
import { ValidationError, validationErrorSchema } from './validationError.js';

export interface Employee {
  /** The Xero identifier for an employee e.g. 297c2dc5-cc47-4afd-8ec8-74990b8761e9 */
  employeeID?: string;
  externalLink?: ExternalLink;
  /** First name of an employee (max length = 255) */
  firstName?: string;
  /** Last name of an employee (max length = 255) */
  lastName?: string;
  /** Current status of an employee – see contact status types */
  status?: Status10Enum;
  /** A string to indicate if a invoice status */
  statusAttributeString?: string;
  updatedDateUTC?: string;
  /** Displays array of validation error messages from the API */
  validationErrors?: ValidationError[];
}

export const employeeSchema: Schema<Employee> = lazy(() =>
  object({
    employeeID: ['EmployeeID', optional(string())],
    externalLink: ['ExternalLink', optional(externalLinkSchema)],
    firstName: ['FirstName', optional(string())],
    lastName: ['LastName', optional(string())],
    status: ['Status', optional(status10EnumSchema)],
    statusAttributeString: ['StatusAttributeString', optional(string())],
    updatedDateUTC: ['UpdatedDateUTC', optional(string())],
    validationErrors: [
      'ValidationErrors',
      optional(array(validationErrorSchema)),
    ],
  })
);
