/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { Employee, employeeSchema } from './employee.js';

export interface Employees {
  employees?: Employee[];
}

export const employeesSchema: Schema<Employees> = lazy(() =>
  object({ employees: ['Employees', optional(array(employeeSchema))] })
);
