/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { ExpenseClaim, expenseClaimSchema } from './expenseClaim.js';

export interface ExpenseClaims {
  expenseClaims?: ExpenseClaim[];
}

export const expenseClaimsSchema: Schema<ExpenseClaims> = lazy(() =>
  object({
    expenseClaims: ['ExpenseClaims', optional(array(expenseClaimSchema))],
  })
);
