/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { Payment, paymentSchema } from './payment.js';
import { Receipt, receiptSchema } from './receipt.js';
import { Status12Enum, status12EnumSchema } from './status12Enum.js';
import { User, userSchema } from './user.js';

export interface ExpenseClaim {
  /** The amount due to be paid for an expense claim */
  amountDue?: number;
  /** The amount still to pay for an expense claim */
  amountPaid?: number;
  /** Xero generated unique identifier for an expense claim */
  expenseClaimID?: string;
  /** The date when the expense claim is due to be paid YYYY-MM-DD */
  paymentDueDate?: string;
  /** See Payments */
  payments?: Payment[];
  /** The Xero identifier for the Receipt e.g. e59a2c7f-1306-4078-a0f3-73537afcbba9 */
  receiptID?: string;
  receipts?: Receipt[];
  /** The date the expense claim will be reported in Xero YYYY-MM-DD */
  reportingDate?: string;
  /** Current status of an expense claim – see status types */
  status?: Status12Enum;
  /** The total of an expense claim being paid */
  total?: number;
  /** Last modified date UTC format */
  updatedDateUTC?: string;
  user?: User;
}

export const expenseClaimSchema: Schema<ExpenseClaim> = lazy(() =>
  object({
    amountDue: ['AmountDue', optional(number())],
    amountPaid: ['AmountPaid', optional(number())],
    expenseClaimID: ['ExpenseClaimID', optional(string())],
    paymentDueDate: ['PaymentDueDate', optional(string())],
    payments: ['Payments', optional(array(paymentSchema))],
    receiptID: ['ReceiptID', optional(string())],
    receipts: ['Receipts', optional(array(receiptSchema))],
    reportingDate: ['ReportingDate', optional(string())],
    status: ['Status', optional(status12EnumSchema)],
    total: ['Total', optional(number())],
    updatedDateUTC: ['UpdatedDateUTC', optional(string())],
    user: ['User', optional(userSchema)],
  })
);
