/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import { LinkTypeEnum, linkTypeEnumSchema } from './linkTypeEnum.js';

export interface ExternalLink {
  description?: string;
  /** See External link types */
  linkType?: LinkTypeEnum;
  /** URL for service e.g. http://twitter.com/xeroapi */
  url?: string;
}

export const externalLinkSchema: Schema<ExternalLink> = object({
  description: ['Description', optional(string())],
  linkType: ['LinkType', optional(linkTypeEnumSchema)],
  url: ['Url', optional(string())],
});
