/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface HistoryRecord {
  /** Name of branding theme */
  changes?: string;
  /** UTC timestamp of creation date of branding theme */
  dateUTC?: string;
  /** details */
  details?: string;
  /** has a value of 0 */
  user?: string;
}

export const historyRecordSchema: Schema<HistoryRecord> = object({
  changes: ['Changes', optional(string())],
  dateUTC: ['DateUTC', optional(string())],
  details: ['Details', optional(string())],
  user: ['User', optional(string())],
});
