/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { HistoryRecord, historyRecordSchema } from './historyRecord.js';

export interface HistoryRecords {
  historyRecords?: HistoryRecord[];
}

export const historyRecordsSchema: Schema<HistoryRecords> = lazy(() =>
  object({
    historyRecords: ['HistoryRecords', optional(array(historyRecordSchema))],
  })
);
