/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema.js';

export interface ImportSummaryOrganisation {
  present?: boolean;
}

export const importSummaryOrganisationSchema: Schema<ImportSummaryOrganisation> = object(
  { present: ['Present', optional(boolean())] }
);
