/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  ImportSummaryAccounts,
  importSummaryAccountsSchema,
} from './importSummaryAccounts.js';
import {
  ImportSummaryOrganisation,
  importSummaryOrganisationSchema,
} from './importSummaryOrganisation.js';

/** A summary of the import from setup endpoint */
export interface ImportSummary {
  /** A summary of the accounts changes */
  accounts?: ImportSummaryAccounts;
  organisation?: ImportSummaryOrganisation;
}

export const importSummarySchema: Schema<ImportSummary> = lazy(() =>
  object({
    accounts: ['Accounts', optional(importSummaryAccountsSchema)],
    organisation: ['Organisation', optional(importSummaryOrganisationSchema)],
  })
);
