/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import { ImportSummary, importSummarySchema } from './importSummary.js';

export interface ImportSummaryObject {
  /** A summary of the import from setup endpoint */
  importSummary?: ImportSummary;
}

export const importSummaryObjectSchema: Schema<ImportSummaryObject> = lazy(() =>
  object({ importSummary: ['ImportSummary', optional(importSummarySchema)] })
);
