/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, optional, Schema } from '../schema.js';

/** A summary of the accounts changes */
export interface ImportSummaryAccounts {
  /** The number of accounts deleted */
  deleted?: number;
  /** The number of accounts that had an error */
  errored?: number;
  /** The number of locked accounts */
  locked?: number;
  /** The number of new accounts created */
  new?: number;
  /** The number of new or updated accounts */
  newOrUpdated?: number;
  present?: boolean;
  /** The number of system accounts */
  system?: number;
  /** The total number of accounts in the org */
  total?: number;
  /** The number of accounts updated */
  updated?: number;
}

export const importSummaryAccountsSchema: Schema<ImportSummaryAccounts> = object(
  {
    deleted: ['Deleted', optional(number())],
    errored: ['Errored', optional(number())],
    locked: ['Locked', optional(number())],
    new: ['New', optional(number())],
    newOrUpdated: ['NewOrUpdated', optional(number())],
    present: ['Present', optional(boolean())],
    system: ['System', optional(number())],
    total: ['Total', optional(number())],
    updated: ['Updated', optional(number())],
  }
);
