/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema.js';

export interface InvoiceReminder {
  /** setting for on or off */
  enabled?: boolean;
}

export const invoiceReminderSchema: Schema<InvoiceReminder> = object({
  enabled: ['Enabled', optional(boolean())],
});
