/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { Invoice, invoiceSchema } from './invoice.js';

export interface Invoices {
  invoices?: Invoice[];
}

export const invoicesSchema: Schema<Invoices> = lazy(() =>
  object({ invoices: ['Invoices', optional(array(invoiceSchema))] })
);
