/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { Attachment, attachmentSchema } from './attachment.js';
import { Contact, contactSchema } from './contact.js';
import { CreditNote, creditNoteSchema } from './creditNote.js';
import {
  CurrencyCodeEnum,
  currencyCodeEnumSchema,
} from './currencyCodeEnum.js';
import {
  LineAmountTypesEnum,
  lineAmountTypesEnumSchema,
} from './lineAmountTypesEnum.js';
import { LineItem, lineItemSchema } from './lineItem.js';
import { Overpayment, overpaymentSchema } from './overpayment.js';
import { Payment, paymentSchema } from './payment.js';
import { Prepayment, prepaymentSchema } from './prepayment.js';
import { Status5Enum, status5EnumSchema } from './status5Enum.js';
import { Type3Enum, type3EnumSchema } from './type3Enum.js';
import { ValidationError, validationErrorSchema } from './validationError.js';

export interface Invoice {
  /** Sum of all credit notes, over-payments and pre-payments applied to invoice */
  amountCredited?: number;
  /** Amount remaining to be paid on invoice */
  amountDue?: number;
  /** Sum of payments received for invoice */
  amountPaid?: number;
  /** Displays array of attachments from the API */
  attachments?: Attachment[];
  /** See BrandingThemes */
  brandingThemeID?: string;
  /** CIS deduction for UK contractors */
  cISDeduction?: number;
  /** CIS Deduction rate for the organisation */
  cISRate?: number;
  contact?: Contact;
  /** Details of credit notes that have been applied to an invoice */
  creditNotes?: CreditNote[];
  /** 3 letter alpha code for the currency – see list of currency codes */
  currencyCode?: CurrencyCodeEnum;
  /** The currency rate for a multicurrency invoice. If no rate is specified, the XE.com day rate is used. (max length = [18].[6]) */
  currencyRate?: number;
  /** Date invoice was issued – YYYY-MM-DD. If the Date element is not specified it will default to the current date based on the timezone setting of the organisation */
  date?: string;
  /** Date invoice is due – YYYY-MM-DD */
  dueDate?: string;
  /** Shown on sales invoices (Accounts Receivable) when this has been set */
  expectedPaymentDate?: string;
  /** The date the invoice was fully paid. Only returned on fully paid invoices */
  fullyPaidOnDate?: string;
  /** boolean to indicate if an invoice has an attachment */
  hasAttachments?: boolean;
  /** A boolean to indicate if a invoice has an validation errors */
  hasErrors?: boolean;
  /** Xero generated unique identifier for invoice */
  invoiceID?: string;
  /** ACCREC – Unique alpha numeric code identifying invoice (when missing will auto-generate from your Organisation Invoice Settings) (max length = 255) */
  invoiceNumber?: string;
  /** boolean to indicate if an invoice has a discount */
  isDiscounted?: boolean;
  /** Line amounts are exclusive of tax by default if you don’t specify this element. See Line Amount Types */
  lineAmountTypes?: LineAmountTypesEnum;
  /** See LineItems */
  lineItems?: LineItem[];
  /** See Overpayments */
  overpayments?: Overpayment[];
  /** See Payments */
  payments?: Payment[];
  /** Shown on bills (Accounts Payable) when this has been set */
  plannedPaymentDate?: string;
  /** See Prepayments */
  prepayments?: Prepayment[];
  /** ACCREC only – additional reference number */
  reference?: string;
  /** Xero generated unique identifier for repeating invoices */
  repeatingInvoiceID?: string;
  /** Boolean to set whether the invoice in the Xero app should be marked as “sent”. This can be set only on invoices that have been approved */
  sentToContact?: boolean;
  /** See Invoice Status Codes */
  status?: Status5Enum;
  /** A string to indicate if a invoice status */
  statusAttributeString?: string;
  /** Total of invoice excluding taxes */
  subTotal?: number;
  /** Total of Invoice tax inclusive (i.e. SubTotal + TotalTax). This will be ignored if it doesn’t equal the sum of the LineAmounts */
  total?: number;
  /** Total of discounts applied on the invoice line items */
  totalDiscount?: number;
  /** Total tax on invoice */
  totalTax?: number;
  /** See Invoice Types */
  type?: Type3Enum;
  /** Last modified date UTC format */
  updatedDateUTC?: string;
  /** URL link to a source document – shown as “Go to [appName]” in the Xero app */
  url?: string;
  /** Displays array of validation error messages from the API */
  validationErrors?: ValidationError[];
  /** Displays array of warning messages from the API */
  warnings?: ValidationError[];
}

export const invoiceSchema: Schema<Invoice> = lazy(() =>
  object({
    amountCredited: ['AmountCredited', optional(number())],
    amountDue: ['AmountDue', optional(number())],
    amountPaid: ['AmountPaid', optional(number())],
    attachments: ['Attachments', optional(array(attachmentSchema))],
    brandingThemeID: ['BrandingThemeID', optional(string())],
    cISDeduction: ['CISDeduction', optional(number())],
    cISRate: ['CISRate', optional(number())],
    contact: ['Contact', optional(contactSchema)],
    creditNotes: ['CreditNotes', optional(array(creditNoteSchema))],
    currencyCode: ['CurrencyCode', optional(currencyCodeEnumSchema)],
    currencyRate: ['CurrencyRate', optional(number())],
    date: ['Date', optional(string())],
    dueDate: ['DueDate', optional(string())],
    expectedPaymentDate: ['ExpectedPaymentDate', optional(string())],
    fullyPaidOnDate: ['FullyPaidOnDate', optional(string())],
    hasAttachments: ['HasAttachments', optional(boolean())],
    hasErrors: ['HasErrors', optional(boolean())],
    invoiceID: ['InvoiceID', optional(string())],
    invoiceNumber: ['InvoiceNumber', optional(string())],
    isDiscounted: ['IsDiscounted', optional(boolean())],
    lineAmountTypes: ['LineAmountTypes', optional(lineAmountTypesEnumSchema)],
    lineItems: ['LineItems', optional(array(lineItemSchema))],
    overpayments: ['Overpayments', optional(array(overpaymentSchema))],
    payments: ['Payments', optional(array(paymentSchema))],
    plannedPaymentDate: ['PlannedPaymentDate', optional(string())],
    prepayments: ['Prepayments', optional(array(prepaymentSchema))],
    reference: ['Reference', optional(string())],
    repeatingInvoiceID: ['RepeatingInvoiceID', optional(string())],
    sentToContact: ['SentToContact', optional(boolean())],
    status: ['Status', optional(status5EnumSchema)],
    statusAttributeString: ['StatusAttributeString', optional(string())],
    subTotal: ['SubTotal', optional(number())],
    total: ['Total', optional(number())],
    totalDiscount: ['TotalDiscount', optional(number())],
    totalTax: ['TotalTax', optional(number())],
    type: ['Type', optional(type3EnumSchema)],
    updatedDateUTC: ['UpdatedDateUTC', optional(string())],
    url: ['Url', optional(string())],
    validationErrors: [
      'ValidationErrors',
      optional(array(validationErrorSchema)),
    ],
    warnings: ['Warnings', optional(array(validationErrorSchema))],
  })
);
