/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { InvoiceReminder, invoiceReminderSchema } from './invoiceReminder.js';

export interface InvoiceReminders {
  invoiceReminders?: InvoiceReminder[];
}

export const invoiceRemindersSchema: Schema<InvoiceReminders> = lazy(() =>
  object({
    invoiceReminders: [
      'InvoiceReminders',
      optional(array(invoiceReminderSchema)),
    ],
  })
);
