/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { Item, itemSchema } from './item.js';

export interface Items {
  items?: Item[];
}

export const itemsSchema: Schema<Items> = lazy(() =>
  object({ items: ['Items', optional(array(itemSchema))] })
);
