/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { Purchase, purchaseSchema } from './purchase.js';
import { ValidationError, validationErrorSchema } from './validationError.js';

export interface Item {
  /** User defined item code (max length = 30) */
  code: string;
  /** The sales description of the item (max length = 4000) */
  description?: string;
  /** The inventory asset account for the item. The account must be of type INVENTORY. The  COGSAccountCode in PurchaseDetails is also required to create a tracked item */
  inventoryAssetAccountCode?: string;
  /** Boolean value, defaults to true. When IsPurchased is true the item is available for purchase transactions in the Xero UI. If IsPurchased is updated to false then PurchaseDescription and PurchaseDetails values will be nulled. */
  isPurchased?: boolean;
  /** Boolean value, defaults to true. When IsSold is true the item will be available on sales transactions in the Xero UI. If IsSold is updated to false then Description and SalesDetails values will be nulled. */
  isSold?: boolean;
  /** True for items that are tracked as inventory. An item will be tracked as inventory if the InventoryAssetAccountCode and COGSAccountCode are set. */
  isTrackedAsInventory?: boolean;
  /** The Xero identifier for an Item */
  itemID?: string;
  /** The name of the item (max length = 50) */
  name?: string;
  /** The purchase description of the item (max length = 4000) */
  purchaseDescription?: string;
  purchaseDetails?: Purchase;
  /** The quantity of the item on hand */
  quantityOnHand?: number;
  salesDetails?: Purchase;
  /** Status of object */
  statusAttributeString?: string;
  /** The value of the item on hand. Calculated using average cost accounting. */
  totalCostPool?: number;
  /** Last modified date in UTC format */
  updatedDateUTC?: string;
  /** Displays array of validation error messages from the API */
  validationErrors?: ValidationError[];
}

export const itemSchema: Schema<Item> = lazy(() =>
  object({
    code: ['Code', string()],
    description: ['Description', optional(string())],
    inventoryAssetAccountCode: [
      'InventoryAssetAccountCode',
      optional(string()),
    ],
    isPurchased: ['IsPurchased', optional(boolean())],
    isSold: ['IsSold', optional(boolean())],
    isTrackedAsInventory: ['IsTrackedAsInventory', optional(boolean())],
    itemID: ['ItemID', optional(string())],
    name: ['Name', optional(string())],
    purchaseDescription: ['PurchaseDescription', optional(string())],
    purchaseDetails: ['PurchaseDetails', optional(purchaseSchema)],
    quantityOnHand: ['QuantityOnHand', optional(number())],
    salesDetails: ['SalesDetails', optional(purchaseSchema)],
    statusAttributeString: ['StatusAttributeString', optional(string())],
    totalCostPool: ['TotalCostPool', optional(number())],
    updatedDateUTC: ['UpdatedDateUTC', optional(string())],
    validationErrors: [
      'ValidationErrors',
      optional(array(validationErrorSchema)),
    ],
  })
);
