/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { JournalLine, journalLineSchema } from './journalLine.js';
import { SourceTypeEnum, sourceTypeEnumSchema } from './sourceTypeEnum.js';

export interface Journal {
  /** Created date UTC format */
  createdDateUTC?: string;
  /** Date the journal was posted */
  journalDate?: string;
  /** Xero identifier */
  journalID?: string;
  /** See JournalLines */
  journalLines?: JournalLine[];
  /** Xero generated journal number */
  journalNumber?: number;
  /** reference field for additional indetifying information */
  reference?: string;
  /** The identifier for the source transaction (e.g. InvoiceID) */
  sourceID?: string;
  /** The journal source type. The type of transaction that created the journal */
  sourceType?: SourceTypeEnum;
}

export const journalSchema: Schema<Journal> = lazy(() =>
  object({
    createdDateUTC: ['CreatedDateUTC', optional(string())],
    journalDate: ['JournalDate', optional(string())],
    journalID: ['JournalID', optional(string())],
    journalLines: ['JournalLines', optional(array(journalLineSchema))],
    journalNumber: ['JournalNumber', optional(number())],
    reference: ['Reference', optional(string())],
    sourceID: ['SourceID', optional(string())],
    sourceType: ['SourceType', optional(sourceTypeEnumSchema)],
  })
);
