/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { Journal, journalSchema } from './journal.js';

export interface Journals {
  journals?: Journal[];
}

export const journalsSchema: Schema<Journals> = lazy(() =>
  object({ journals: ['Journals', optional(array(journalSchema))] })
);
