/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { AccountTypeEnum, accountTypeEnumSchema } from './accountTypeEnum.js';
import {
  TrackingCategory,
  trackingCategorySchema,
} from './trackingCategory.js';

export interface JournalLine {
  /** See Accounts */
  accountCode?: string;
  /** See Accounts */
  accountID?: string;
  /** See AccountCodes */
  accountName?: string;
  /** See Account Types */
  accountType?: AccountTypeEnum;
  /** The description from the source transaction line item. Only returned if populated. */
  description?: string;
  /** Gross amount of journal line (NetAmount + TaxAmount). */
  grossAmount?: number;
  /** Xero identifier for Journal */
  journalLineID?: string;
  /** Net amount of journal line. This will be a positive value for a debit and negative for a credit */
  netAmount?: number;
  /** Total tax on a journal line */
  taxAmount?: number;
  /** see TaxRates */
  taxName?: string;
  /** The tax type from TaxRates */
  taxType?: string;
  /** Optional Tracking Category – see Tracking. Any JournalLine can have a maximum of 2 <TrackingCategory> elements. */
  trackingCategories?: TrackingCategory[];
}

export const journalLineSchema: Schema<JournalLine> = lazy(() =>
  object({
    accountCode: ['AccountCode', optional(string())],
    accountID: ['AccountID', optional(string())],
    accountName: ['AccountName', optional(string())],
    accountType: ['AccountType', optional(accountTypeEnumSchema)],
    description: ['Description', optional(string())],
    grossAmount: ['GrossAmount', optional(number())],
    journalLineID: ['JournalLineID', optional(string())],
    netAmount: ['NetAmount', optional(number())],
    taxAmount: ['TaxAmount', optional(number())],
    taxName: ['TaxName', optional(string())],
    taxType: ['TaxType', optional(string())],
    trackingCategories: [
      'TrackingCategories',
      optional(array(trackingCategorySchema)),
    ],
  })
);
