/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for LineAmountTypesEnum
 */
export enum LineAmountTypesEnum {
  Exclusive = 'Exclusive',
  Inclusive = 'Inclusive',
  NoTax = 'NoTax',
}

/**
 * Schema for LineAmountTypesEnum
 */
export const lineAmountTypesEnumSchema: Schema<LineAmountTypesEnum> = stringEnum(
  LineAmountTypesEnum
);
