/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import {
  LineItemTracking,
  lineItemTrackingSchema,
} from './lineItemTracking.js';

export interface LineItem {
  /** See Accounts */
  accountCode?: string;
  /** Description needs to be at least 1 char long. A line item with just a description (i.e no unit amount or quantity) can be created by specifying just a <Description> element that contains at least 1 character */
  description?: string;
  /** Discount amount being applied to a line item. Only supported on ACCREC invoices - ACCPAY invoices and credit notes in Xero do not support discounts. */
  discountAmount?: number;
  /** Percentage discount being applied to a line item (only supported on  ACCREC invoices – ACC PAY invoices and credit notes in Xero do not support discounts */
  discountRate?: number;
  /** See Items */
  itemCode?: string;
  /** If you wish to omit either of the <Quantity> or <UnitAmount> you can provide a LineAmount and Xero will calculate the missing amount for you. The line amount reflects the discounted price if a DiscountRate has been used . i.e LineAmount = Quantity * Unit Amount * ((100 – DiscountRate)/100) */
  lineAmount?: number;
  /** LineItem unique ID */
  lineItemID?: string;
  /** LineItem Quantity */
  quantity?: number;
  /** The Xero identifier for a Repeating Invoice */
  repeatingInvoiceID?: string;
  /** The tax amount is auto calculated as a percentage of the line amount (see below) based on the tax rate. This value can be overriden if the calculated <TaxAmount> is not correct. */
  taxAmount?: number;
  /** The tax type from TaxRates */
  taxType?: string;
  /** Optional Tracking Category – see Tracking.  Any LineItem can have a  maximum of 2 <TrackingCategory> elements. */
  tracking?: LineItemTracking[];
  /** LineItem Unit Amount */
  unitAmount?: number;
}

export const lineItemSchema: Schema<LineItem> = lazy(() =>
  object({
    accountCode: ['AccountCode', optional(string())],
    description: ['Description', optional(string())],
    discountAmount: ['DiscountAmount', optional(number())],
    discountRate: ['DiscountRate', optional(number())],
    itemCode: ['ItemCode', optional(string())],
    lineAmount: ['LineAmount', optional(number())],
    lineItemID: ['LineItemID', optional(string())],
    quantity: ['Quantity', optional(number())],
    repeatingInvoiceID: ['RepeatingInvoiceID', optional(string())],
    taxAmount: ['TaxAmount', optional(number())],
    taxType: ['TaxType', optional(string())],
    tracking: ['Tracking', optional(array(lineItemTrackingSchema))],
    unitAmount: ['UnitAmount', optional(number())],
  })
);
