/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface LineItemTracking {
  /** The name of the tracking category */
  name?: string;
  /** See Tracking Options */
  option?: string;
  /** The Xero identifier for a tracking category */
  trackingCategoryID?: string;
  /** The Xero identifier for a tracking category option */
  trackingOptionID?: string;
}

export const lineItemTrackingSchema: Schema<LineItemTracking> = object({
  name: ['Name', optional(string())],
  option: ['Option', optional(string())],
  trackingCategoryID: ['TrackingCategoryID', optional(string())],
  trackingOptionID: ['TrackingOptionID', optional(string())],
});
