/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import {
  LinkedTransaction,
  linkedTransactionSchema,
} from './linkedTransaction.js';

export interface LinkedTransactions {
  linkedTransactions?: LinkedTransaction[];
}

export const linkedTransactionsSchema: Schema<LinkedTransactions> = lazy(() =>
  object({
    linkedTransactions: [
      'LinkedTransactions',
      optional(array(linkedTransactionSchema)),
    ],
  })
);
