/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import {
  SourceTransactionTypeCodeEnum,
  sourceTransactionTypeCodeEnumSchema,
} from './sourceTransactionTypeCodeEnum.js';
import { Status15Enum, status15EnumSchema } from './status15Enum.js';
import { Type7Enum, type7EnumSchema } from './type7Enum.js';
import { ValidationError, validationErrorSchema } from './validationError.js';

export interface LinkedTransaction {
  /** Filter by the combination of ContactID and Status. Get all the linked transactions that have been assigned to a particular customer and have a particular status e.g. GET /LinkedTransactions?ContactID=4bb34b03-3378-4bb2-a0ed-6345abf3224e&Status=APPROVED. */
  contactID?: string;
  /** The Xero identifier for an Linked Transaction e.g./LinkedTransactions/297c2dc5-cc47-4afd-8ec8-74990b8761e9 */
  linkedTransactionID?: string;
  /** The line item identifier from the source transaction. */
  sourceLineItemID?: string;
  /** Filter by the SourceTransactionID. Get all the linked transactions created from a particular ACCPAY invoice */
  sourceTransactionID?: string;
  /** The Type of the source tranasction. This will be ACCPAY if the linked transaction was created from an invoice and SPEND if it was created from a bank transaction. */
  sourceTransactionTypeCode?: SourceTransactionTypeCodeEnum;
  /** Filter by the combination of ContactID and Status. Get all the linked transactions that have been assigned to a particular customer and have a particular status e.g. GET /LinkedTransactions?ContactID=4bb34b03-3378-4bb2-a0ed-6345abf3224e&Status=APPROVED. */
  status?: Status15Enum;
  /** The line item identifier from the target transaction. It is possible  to link multiple billable expenses to the same TargetLineItemID. */
  targetLineItemID?: string;
  /** Filter by the TargetTransactionID. Get all the linked transactions  allocated to a particular ACCREC invoice */
  targetTransactionID?: string;
  /** This will always be BILLABLEEXPENSE. More types may be added in future. */
  type?: Type7Enum;
  /** The last modified date in UTC format */
  updatedDateUTC?: string;
  /** Displays array of validation error messages from the API */
  validationErrors?: ValidationError[];
}

export const linkedTransactionSchema: Schema<LinkedTransaction> = lazy(() =>
  object({
    contactID: ['ContactID', optional(string())],
    linkedTransactionID: ['LinkedTransactionID', optional(string())],
    sourceLineItemID: ['SourceLineItemID', optional(string())],
    sourceTransactionID: ['SourceTransactionID', optional(string())],
    sourceTransactionTypeCode: [
      'SourceTransactionTypeCode',
      optional(sourceTransactionTypeCodeEnumSchema),
    ],
    status: ['Status', optional(status15EnumSchema)],
    targetLineItemID: ['TargetLineItemID', optional(string())],
    targetTransactionID: ['TargetTransactionID', optional(string())],
    type: ['Type', optional(type7EnumSchema)],
    updatedDateUTC: ['UpdatedDateUTC', optional(string())],
    validationErrors: [
      'ValidationErrors',
      optional(array(validationErrorSchema)),
    ],
  })
);
