/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for LinkTypeEnum
 */
export enum LinkTypeEnum {
  Facebook = 'Facebook',
  GooglePlus = 'GooglePlus',
  LinkedIn = 'LinkedIn',
  Twitter = 'Twitter',
  Website = 'Website',
}

/**
 * Schema for LinkTypeEnum
 */
export const linkTypeEnumSchema: Schema<LinkTypeEnum> = stringEnum(
  LinkTypeEnum
);
