/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { ManualJournal, manualJournalSchema } from './manualJournal.js';

export interface ManualJournals {
  manualJournals?: ManualJournal[];
}

export const manualJournalsSchema: Schema<ManualJournals> = lazy(() =>
  object({
    manualJournals: ['ManualJournals', optional(array(manualJournalSchema))],
  })
);
