/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import {
  TrackingCategory,
  trackingCategorySchema,
} from './trackingCategory.js';

export interface ManualJournalLine {
  /** See Accounts */
  accountCode?: string;
  /** See Accounts */
  accountID?: string;
  /** Description for journal line */
  description?: string;
  /** is the line blank */
  isBlank?: boolean;
  /** total for line. Debits are positive, credits are negative value */
  lineAmount?: number;
  /** The calculated tax amount based on the TaxType and LineAmount */
  taxAmount?: number;
  /** The tax type from TaxRates */
  taxType?: string;
  /** Optional Tracking Category – see Tracking. Any JournalLine can have a maximum of 2 <TrackingCategory> elements. */
  tracking?: TrackingCategory[];
}

export const manualJournalLineSchema: Schema<ManualJournalLine> = lazy(() =>
  object({
    accountCode: ['AccountCode', optional(string())],
    accountID: ['AccountID', optional(string())],
    description: ['Description', optional(string())],
    isBlank: ['IsBlank', optional(boolean())],
    lineAmount: ['LineAmount', optional(number())],
    taxAmount: ['TaxAmount', optional(number())],
    taxType: ['TaxType', optional(string())],
    tracking: ['Tracking', optional(array(trackingCategorySchema))],
  })
);
