/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { Attachment, attachmentSchema } from './attachment.js';
import {
  LineAmountTypesEnum,
  lineAmountTypesEnumSchema,
} from './lineAmountTypesEnum.js';
import {
  ManualJournalLine,
  manualJournalLineSchema,
} from './manualJournalLine.js';
import { Status16Enum, status16EnumSchema } from './status16Enum.js';
import { ValidationError, validationErrorSchema } from './validationError.js';

export interface ManualJournal {
  /** Displays array of attachments from the API */
  attachments?: Attachment[];
  /** Date journal was posted – YYYY-MM-DD */
  date?: string;
  /** Boolean to indicate if a manual journal has an attachment */
  hasAttachments?: boolean;
  /** See JournalLines */
  journalLines?: ManualJournalLine[];
  /** Line amounts are exclusive of tax by default if you don’t specify this element. See Line Amount Types */
  lineAmountTypes?: LineAmountTypesEnum;
  /** The Xero identifier for a Manual Journal */
  manualJournalID?: string;
  /** Description of journal being posted */
  narration: string;
  /** Boolean – default is true if not specified */
  showOnCashBasisReports?: boolean;
  /** See Manual Journal Status Codes */
  status?: Status16Enum;
  /** A string to indicate if a invoice status */
  statusAttributeString?: string;
  /** Last modified date UTC format */
  updatedDateUTC?: string;
  /** Url link to a source document – shown as “Go to [appName]” in the Xero app */
  url?: string;
  /** Displays array of validation error messages from the API */
  validationErrors?: ValidationError[];
  /** Displays array of warning messages from the API */
  warnings?: ValidationError[];
}

export const manualJournalSchema: Schema<ManualJournal> = lazy(() =>
  object({
    attachments: ['Attachments', optional(array(attachmentSchema))],
    date: ['Date', optional(string())],
    hasAttachments: ['HasAttachments', optional(boolean())],
    journalLines: ['JournalLines', optional(array(manualJournalLineSchema))],
    lineAmountTypes: ['LineAmountTypes', optional(lineAmountTypesEnumSchema)],
    manualJournalID: ['ManualJournalID', optional(string())],
    narration: ['Narration', string()],
    showOnCashBasisReports: ['ShowOnCashBasisReports', optional(boolean())],
    status: ['Status', optional(status16EnumSchema)],
    statusAttributeString: ['StatusAttributeString', optional(string())],
    updatedDateUTC: ['UpdatedDateUTC', optional(string())],
    url: ['Url', optional(string())],
    validationErrors: [
      'ValidationErrors',
      optional(array(validationErrorSchema)),
    ],
    warnings: ['Warnings', optional(array(validationErrorSchema))],
  })
);
