/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for OAuthScopeEnum
 */
export enum OAuthScopeEnum {
  AccountingAttachments = 'accounting.attachments',
  AccountingAttachmentsRead = 'accounting.attachments.read',
  AccountingContacts = 'accounting.contacts',
  AccountingContactsRead = 'accounting.contacts.read',
  AccountingJournalsRead = 'accounting.journals.read',
  AccountingReportsRead = 'accounting.reports.read',
  AccountingReportsTenninetynineRead = 'accounting.reports.tenninetynine.read',
  AccountingSettings = 'accounting.settings',
  AccountingSettingsRead = 'accounting.settings.read',
  AccountingTransactions = 'accounting.transactions',
  AccountingTransactionsRead = 'accounting.transactions.read',
  Assets = 'assets',
  AssetsRead = 'assets.read',
  Bankfeeds = 'bankfeeds',
  Email = 'email',
  Files = 'files',
  FilesRead = 'files.read',
  Openid = 'openid',
  Paymentservices = 'paymentservices',
  Payroll = 'payroll',
  PayrollEmployees = 'payroll.employees',
  PayrollEmployeesRead = 'payroll.employees.read',
  PayrollLeaveapplications = 'payroll.leaveapplications',
  PayrollLeaveapplicationsRead = 'payroll.leaveapplications.read',
  PayrollPayitems = 'payroll.payitems',
  PayrollPayitemsRead = 'payroll.payitems.read',
  PayrollPayrollcalendars = 'payroll.payrollcalendars',
  PayrollPayrollcalendarsRead = 'payroll.payrollcalendars.read',
  PayrollPayruns = 'payroll.payruns',
  PayrollPayrunsRead = 'payroll.payruns.read',
  PayrollPayslip = 'payroll.payslip',
  PayrollPayslipRead = 'payroll.payslip.read',
  PayrollRead = 'payroll.read',
  PayrollSettingsRead = 'payroll.settings.read',
  PayrollSuperfundproductsRead = 'payroll.superfundproducts.read',
  PayrollSuperfunds = 'payroll.superfunds',
  PayrollSuperfundsRead = 'payroll.superfunds.read',
  PayrollTimesheets = 'payroll.timesheets',
  PayrollTimesheetsRead = 'payroll.timesheets.read',
  Profile = 'profile',
  Projects = 'projects',
  ProjectsRead = 'projects.read',
}

/**
 * Schema for OAuthScopeEnum
 */
export const oAuthScopeEnumSchema: Schema<OAuthScopeEnum> = stringEnum(
  OAuthScopeEnum
);
