/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface OnlineInvoice {
  /** the URL to an online invoice */
  onlineInvoiceUrl?: string;
}

export const onlineInvoiceSchema: Schema<OnlineInvoice> = object({
  onlineInvoiceUrl: ['OnlineInvoiceUrl', optional(string())],
});
