/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { OnlineInvoice, onlineInvoiceSchema } from './onlineInvoice.js';

export interface OnlineInvoices {
  onlineInvoices?: OnlineInvoice[];
}

export const onlineInvoicesSchema: Schema<OnlineInvoices> = lazy(() =>
  object({
    onlineInvoices: ['OnlineInvoices', optional(array(onlineInvoiceSchema))],
  })
);
