/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for OrganisationRoleEnum
 */
export enum OrganisationRoleEnum {
  READONLY = 'READONLY',
  INVOICEONLY = 'INVOICEONLY',
  STANDARD = 'STANDARD',
  FINANCIALADVISER = 'FINANCIALADVISER',
  MANAGEDCLIENT = 'MANAGEDCLIENT',
  CASHBOOKCLIENT = 'CASHBOOKCLIENT',
  UNKNOWN = 'UNKNOWN',
}

/**
 * Schema for OrganisationRoleEnum
 */
export const organisationRoleEnumSchema: Schema<OrganisationRoleEnum> = stringEnum(
  OrganisationRoleEnum
);
