/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { Organisation, organisationSchema } from './organisation.js';

export interface Organisations {
  organisations?: Organisation[];
}

export const organisationsSchema: Schema<Organisations> = lazy(() =>
  object({
    organisations: ['Organisations', optional(array(organisationSchema))],
  })
);
