/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import {
  AddressForOrganisation,
  addressForOrganisationSchema,
} from './addressForOrganisation.js';
import { Class1Enum, class1EnumSchema } from './class1Enum.js';
import { CountryCodeEnum, countryCodeEnumSchema } from './countryCodeEnum.js';
import {
  CurrencyCodeEnum,
  currencyCodeEnumSchema,
} from './currencyCodeEnum.js';
import { EditionEnum, editionEnumSchema } from './editionEnum.js';
import { ExternalLink, externalLinkSchema } from './externalLink.js';
import {
  OrganisationEntityTypeEnum,
  organisationEntityTypeEnumSchema,
} from './organisationEntityTypeEnum.js';
import {
  OrganisationTypeEnum,
  organisationTypeEnumSchema,
} from './organisationTypeEnum.js';
import { PaymentTerm, paymentTermSchema } from './paymentTerm.js';
import { Phone, phoneSchema } from './phone.js';
import {
  SalesTaxBasisEnum,
  salesTaxBasisEnumSchema,
} from './salesTaxBasisEnum.js';
import {
  SalesTaxPeriodEnum,
  salesTaxPeriodEnumSchema,
} from './salesTaxPeriodEnum.js';
import { TimeZoneEnum, timeZoneEnumSchema } from './timeZoneEnum.js';
import { VersionEnum, versionEnumSchema } from './versionEnum.js';

export interface Organisation {
  /** Display a unique key used for Xero-to-Xero transactions */
  aPIKey?: string;
  /** Address details for organisation – see Addresses */
  addresses?: AddressForOrganisation[];
  /** 3 letter alpha code for the currency – see list of currency codes */
  baseCurrency?: CurrencyCodeEnum;
  /** Organisation Classes describe which plan the Xero organisation is on (e.g. DEMO, TRIAL, PREMIUM) */
  mClass?: Class1Enum;
  countryCode?: CountryCodeEnum;
  /** Timestamp when the organisation was created in Xero */
  createdDateUTC?: string;
  /** The default for LineAmountTypes on purchase transactions */
  defaultPurchasesTax?: string;
  /** The default for LineAmountTypes on sales transactions */
  defaultSalesTax?: string;
  /** BUSINESS or PARTNER. Partner edition organisations are sold exclusively through accounting partners and have restricted functionality (e.g. no access to invoicing) */
  edition?: EditionEnum;
  /** Shown if set. US Only. */
  employerIdentificationNumber?: string;
  /** Shown if set. See lock dates */
  endOfYearLockDate?: string;
  /** Organisation profile links for popular services such as Facebook,Twitter, GooglePlus and LinkedIn. You can also add link to your website here. Shown if Organisation settings  is updated in Xero. See ExternalLinks below */
  externalLinks?: ExternalLink[];
  /** Calendar day e.g. 0-31 */
  financialYearEndDay?: number;
  /** Calendar Month e.g. 1-12 */
  financialYearEndMonth?: number;
  /** Boolean to describe if organisation is a demo company. */
  isDemoCompany?: boolean;
  /** Organisation name shown on Reports */
  legalName?: string;
  /** Description of business type as defined in Organisation settings */
  lineOfBusiness?: string;
  /** Display name of organisation shown in Xero */
  name?: string;
  /** Organisation Entity Type */
  organisationEntityType?: OrganisationEntityTypeEnum;
  /** Unique Xero identifier */
  organisationID?: string;
  /** Will be set to ACTIVE if you can connect to organisation via the Xero API */
  organisationStatus?: string;
  /** Organisation Type */
  organisationType?: OrganisationTypeEnum;
  paymentTerms?: PaymentTerm;
  /** Boolean to describe if organisation is registered with a local tax authority i.e. true, false */
  paysTax?: boolean;
  /** Shown if set. See lock dates */
  periodLockDate?: string;
  /** Phones details for organisation – see Phones */
  phones?: Phone[];
  /** Shows for New Zealand, Australian and UK organisations */
  registrationNumber?: string;
  /** The accounting basis used for tax returns. See Sales Tax Basis */
  salesTaxBasis?: SalesTaxBasisEnum;
  /** The frequency with which tax returns are processed. See Sales Tax Period */
  salesTaxPeriod?: SalesTaxPeriodEnum;
  /** A unique identifier for the organisation. Potential uses. */
  shortCode?: string;
  /** Shown if set. Displays in the Xero UI as Tax File Number (AU), GST Number (NZ), VAT Number (UK) and Tax ID Number (US & Global). */
  taxNumber?: string;
  /** Timezone specifications */
  timezone?: TimeZoneEnum;
  /** See Version Types */
  version?: VersionEnum;
}

export const organisationSchema: Schema<Organisation> = lazy(() =>
  object({
    aPIKey: ['APIKey', optional(string())],
    addresses: ['Addresses', optional(array(addressForOrganisationSchema))],
    baseCurrency: ['BaseCurrency', optional(currencyCodeEnumSchema)],
    mClass: ['Class', optional(class1EnumSchema)],
    countryCode: ['CountryCode', optional(countryCodeEnumSchema)],
    createdDateUTC: ['CreatedDateUTC', optional(string())],
    defaultPurchasesTax: ['DefaultPurchasesTax', optional(string())],
    defaultSalesTax: ['DefaultSalesTax', optional(string())],
    edition: ['Edition', optional(editionEnumSchema)],
    employerIdentificationNumber: [
      'EmployerIdentificationNumber',
      optional(string()),
    ],
    endOfYearLockDate: ['EndOfYearLockDate', optional(string())],
    externalLinks: ['ExternalLinks', optional(array(externalLinkSchema))],
    financialYearEndDay: ['FinancialYearEndDay', optional(number())],
    financialYearEndMonth: ['FinancialYearEndMonth', optional(number())],
    isDemoCompany: ['IsDemoCompany', optional(boolean())],
    legalName: ['LegalName', optional(string())],
    lineOfBusiness: ['LineOfBusiness', optional(string())],
    name: ['Name', optional(string())],
    organisationEntityType: [
      'OrganisationEntityType',
      optional(organisationEntityTypeEnumSchema),
    ],
    organisationID: ['OrganisationID', optional(string())],
    organisationStatus: ['OrganisationStatus', optional(string())],
    organisationType: [
      'OrganisationType',
      optional(organisationTypeEnumSchema),
    ],
    paymentTerms: ['PaymentTerms', optional(paymentTermSchema)],
    paysTax: ['PaysTax', optional(boolean())],
    periodLockDate: ['PeriodLockDate', optional(string())],
    phones: ['Phones', optional(array(phoneSchema))],
    registrationNumber: ['RegistrationNumber', optional(string())],
    salesTaxBasis: ['SalesTaxBasis', optional(salesTaxBasisEnumSchema)],
    salesTaxPeriod: ['SalesTaxPeriod', optional(salesTaxPeriodEnumSchema)],
    shortCode: ['ShortCode', optional(string())],
    taxNumber: ['TaxNumber', optional(string())],
    timezone: ['Timezone', optional(timeZoneEnumSchema)],
    version: ['Version', optional(versionEnumSchema)],
  })
);
