/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for OrganisationEntityTypeEnum
 */
export enum OrganisationEntityTypeEnum {
  ACCOUNTINGPRACTICE = 'ACCOUNTING_PRACTICE',
  COMPANY = 'COMPANY',
  CHARITY = 'CHARITY',
  CLUBORSOCIETY = 'CLUB_OR_SOCIETY',
  LOOKTHROUGHCOMPANY = 'LOOK_THROUGH_COMPANY',
  NOTFORPROFIT = 'NOT_FOR_PROFIT',
  PARTNERSHIP = 'PARTNERSHIP',
  SCORPORATION = 'S_CORPORATION',
  SELFMANAGEDSUPERANNUATIONFUND = 'SELF_MANAGED_SUPERANNUATION_FUND',
  SOLETRADER = 'SOLE_TRADER',
  SUPERANNUATIONFUND = 'SUPERANNUATION_FUND',
  TRUST = 'TRUST',
}

/**
 * Schema for OrganisationEntityTypeEnum
 */
export const organisationEntityTypeEnumSchema: Schema<OrganisationEntityTypeEnum> = stringEnum(
  OrganisationEntityTypeEnum
);
