/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { Overpayment, overpaymentSchema } from './overpayment.js';

export interface Overpayments {
  overpayments?: Overpayment[];
}

export const overpaymentsSchema: Schema<Overpayments> = lazy(() =>
  object({ overpayments: ['Overpayments', optional(array(overpaymentSchema))] })
);
