/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { Allocation, allocationSchema } from './allocation.js';
import { Attachment, attachmentSchema } from './attachment.js';
import { Contact, contactSchema } from './contact.js';
import {
  CurrencyCodeEnum,
  currencyCodeEnumSchema,
} from './currencyCodeEnum.js';
import {
  LineAmountTypesEnum,
  lineAmountTypesEnumSchema,
} from './lineAmountTypesEnum.js';
import { LineItem, lineItemSchema } from './lineItem.js';
import { Payment, paymentSchema } from './payment.js';
import { Status3Enum, status3EnumSchema } from './status3Enum.js';
import { Type1Enum, type1EnumSchema } from './type1Enum.js';

export interface Overpayment {
  /** See Allocations */
  allocations?: Allocation[];
  /** The amount of applied to an invoice */
  appliedAmount?: number;
  /** See Attachments */
  attachments?: Attachment[];
  contact?: Contact;
  /** 3 letter alpha code for the currency – see list of currency codes */
  currencyCode?: CurrencyCodeEnum;
  /** The currency rate for a multicurrency overpayment. If no rate is specified, the XE.com day rate is used */
  currencyRate?: number;
  /** The date the overpayment is created YYYY-MM-DD */
  date?: string;
  /** boolean to indicate if a overpayment has an attachment */
  hasAttachments?: boolean;
  /** Line amounts are exclusive of tax by default if you don’t specify this element. See Line Amount Types */
  lineAmountTypes?: LineAmountTypesEnum;
  /** See Overpayment Line Items */
  lineItems?: LineItem[];
  /** Xero generated unique identifier */
  overpaymentID?: string;
  /** See Payments */
  payments?: Payment[];
  /** The remaining credit balance on the overpayment */
  remainingCredit?: number;
  /** See Overpayment Status Codes */
  status?: Status3Enum;
  /** The subtotal of the overpayment excluding taxes */
  subTotal?: number;
  /** The total of the overpayment (subtotal + total tax) */
  total?: number;
  /** The total tax on the overpayment */
  totalTax?: number;
  /** See Overpayment Types */
  type?: Type1Enum;
  /** UTC timestamp of last update to the overpayment */
  updatedDateUTC?: string;
}

export const overpaymentSchema: Schema<Overpayment> = lazy(() =>
  object({
    allocations: ['Allocations', optional(array(allocationSchema))],
    appliedAmount: ['AppliedAmount', optional(number())],
    attachments: ['Attachments', optional(array(attachmentSchema))],
    contact: ['Contact', optional(contactSchema)],
    currencyCode: ['CurrencyCode', optional(currencyCodeEnumSchema)],
    currencyRate: ['CurrencyRate', optional(number())],
    date: ['Date', optional(string())],
    hasAttachments: ['HasAttachments', optional(boolean())],
    lineAmountTypes: ['LineAmountTypes', optional(lineAmountTypesEnumSchema)],
    lineItems: ['LineItems', optional(array(lineItemSchema))],
    overpaymentID: ['OverpaymentID', optional(string())],
    payments: ['Payments', optional(array(paymentSchema))],
    remainingCredit: ['RemainingCredit', optional(number())],
    status: ['Status', optional(status3EnumSchema)],
    subTotal: ['SubTotal', optional(number())],
    total: ['Total', optional(number())],
    totalTax: ['TotalTax', optional(number())],
    type: ['Type', optional(type1EnumSchema)],
    updatedDateUTC: ['UpdatedDateUTC', optional(string())],
  })
);
