/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { Account, accountSchema } from './account.js';
import { CreditNote, creditNoteSchema } from './creditNote.js';
import { Invoice, invoiceSchema } from './invoice.js';
import { Overpayment, overpaymentSchema } from './overpayment.js';
import { PaymentTypeEnum, paymentTypeEnumSchema } from './paymentTypeEnum.js';
import { Prepayment, prepaymentSchema } from './prepayment.js';
import { Status6Enum, status6EnumSchema } from './status6Enum.js';
import { ValidationError, validationErrorSchema } from './validationError.js';

export interface Payment {
  account?: Account;
  /** The amount of the payment. Must be less than or equal to the outstanding amount owing on the invoice e.g. 200.00 */
  amount?: number;
  /** The suppliers bank account number the payment is being made to */
  bankAccountNumber?: string;
  /** Present if the payment was created as part of a batch. */
  batchPaymentID?: string;
  /** Code of account you are using to make the payment e.g. 001 (note- not all accounts have a code value) */
  code?: string;
  creditNote?: CreditNote;
  /** Number of invoice or credit note you are applying payment to e.g. INV-4003 */
  creditNoteNumber?: string;
  /** Exchange rate when payment is received. Only used for non base currency invoices and credit notes e.g. 0.7500 */
  currencyRate?: number;
  /** Date the payment is being made (YYYY-MM-DD) e.g. 2009-09-06 */
  date?: string;
  /** The information to appear on the supplier's bank account */
  details?: string;
  /** A boolean to indicate if a contact has an validation errors */
  hasAccount?: boolean;
  /** A boolean to indicate if a contact has an validation errors */
  hasValidationErrors?: boolean;
  invoice?: Invoice;
  /** Number of invoice or credit note you are applying payment to e.g.INV-4003 */
  invoiceNumber?: string;
  /** An optional parameter for the payment. A boolean indicating whether you would like the payment to be created as reconciled when using PUT, or whether a payment has been reconciled when using GET */
  isReconciled?: boolean;
  overpayment?: Overpayment;
  /** The suppliers bank account number the payment is being made to */
  particulars?: string;
  /** The Xero identifier for an Payment e.g. 297c2dc5-cc47-4afd-8ec8-74990b8761e9 */
  paymentID?: string;
  /** See Payment Types. */
  paymentType?: PaymentTypeEnum;
  prepayment?: Prepayment;
  /** An optional description for the payment e.g. Direct Debit */
  reference?: string;
  /** The status of the payment. */
  status?: Status6Enum;
  /** A string to indicate if a invoice status */
  statusAttributeString?: string;
  /** UTC timestamp of last update to the payment */
  updatedDateUTC?: string;
  /** Displays array of validation error messages from the API */
  validationErrors?: ValidationError[];
}

export const paymentSchema: Schema<Payment> = lazy(() =>
  object({
    account: ['Account', optional(accountSchema)],
    amount: ['Amount', optional(number())],
    bankAccountNumber: ['BankAccountNumber', optional(string())],
    batchPaymentID: ['BatchPaymentID', optional(string())],
    code: ['Code', optional(string())],
    creditNote: ['CreditNote', optional(creditNoteSchema)],
    creditNoteNumber: ['CreditNoteNumber', optional(string())],
    currencyRate: ['CurrencyRate', optional(number())],
    date: ['Date', optional(string())],
    details: ['Details', optional(string())],
    hasAccount: ['HasAccount', optional(boolean())],
    hasValidationErrors: ['HasValidationErrors', optional(boolean())],
    invoice: ['Invoice', optional(invoiceSchema)],
    invoiceNumber: ['InvoiceNumber', optional(string())],
    isReconciled: ['IsReconciled', optional(boolean())],
    overpayment: ['Overpayment', optional(overpaymentSchema)],
    particulars: ['Particulars', optional(string())],
    paymentID: ['PaymentID', optional(string())],
    paymentType: ['PaymentType', optional(paymentTypeEnumSchema)],
    prepayment: ['Prepayment', optional(prepaymentSchema)],
    reference: ['Reference', optional(string())],
    status: ['Status', optional(status6EnumSchema)],
    statusAttributeString: ['StatusAttributeString', optional(string())],
    updatedDateUTC: ['UpdatedDateUTC', optional(string())],
    validationErrors: [
      'ValidationErrors',
      optional(array(validationErrorSchema)),
    ],
  })
);
