/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PaymentTypeEnum
 */
export enum PaymentTypeEnum {
  ACCRECPAYMENT = 'ACCRECPAYMENT',
  ACCPAYPAYMENT = 'ACCPAYPAYMENT',
  ARCREDITPAYMENT = 'ARCREDITPAYMENT',
  APCREDITPAYMENT = 'APCREDITPAYMENT',
  AROVERPAYMENTPAYMENT = 'AROVERPAYMENTPAYMENT',
  ARPREPAYMENTPAYMENT = 'ARPREPAYMENTPAYMENT',
  APPREPAYMENTPAYMENT = 'APPREPAYMENTPAYMENT',
  APOVERPAYMENTPAYMENT = 'APOVERPAYMENTPAYMENT',
}

/**
 * Schema for PaymentTypeEnum
 */
export const paymentTypeEnumSchema: Schema<PaymentTypeEnum> = stringEnum(
  PaymentTypeEnum
);
