/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PaymentTermTypeEnum
 */
export enum PaymentTermTypeEnum {
  DAYSAFTERBILLDATE = 'DAYSAFTERBILLDATE',
  DAYSAFTERBILLMONTH = 'DAYSAFTERBILLMONTH',
  OFCURRENTMONTH = 'OFCURRENTMONTH',
  OFFOLLOWINGMONTH = 'OFFOLLOWINGMONTH',
}

/**
 * Schema for PaymentTermTypeEnum
 */
export const paymentTermTypeEnumSchema: Schema<PaymentTermTypeEnum> = stringEnum(
  PaymentTermTypeEnum
);
