/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import { ValidationError, validationErrorSchema } from './validationError.js';

export interface PaymentService {
  /** The text displayed on the Pay Now button in Xero Online Invoicing. If this is not set it will default to Pay by credit card */
  payNowText?: string;
  /** Xero identifier */
  paymentServiceID?: string;
  /** Name of payment service */
  paymentServiceName?: string;
  /** This will always be CUSTOM for payment services created via the API. */
  paymentServiceType?: string;
  /** The custom payment URL */
  paymentServiceUrl?: string;
  /** Displays array of validation error messages from the API */
  validationErrors?: ValidationError[];
}

export const paymentServiceSchema: Schema<PaymentService> = lazy(() =>
  object({
    payNowText: ['PayNowText', optional(string())],
    paymentServiceID: ['PaymentServiceID', optional(string())],
    paymentServiceName: ['PaymentServiceName', optional(string())],
    paymentServiceType: ['PaymentServiceType', optional(string())],
    paymentServiceUrl: ['PaymentServiceUrl', optional(string())],
    validationErrors: [
      'ValidationErrors',
      optional(array(validationErrorSchema)),
    ],
  })
);
