/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import { Bill, billSchema } from './bill.js';

export interface PaymentTerm {
  bills?: Bill;
  sales?: Bill;
}

export const paymentTermSchema: Schema<PaymentTerm> = lazy(() =>
  object({
    bills: ['Bills', optional(billSchema)],
    sales: ['Sales', optional(billSchema)],
  })
);
