/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface PaymentDelete {
  /** The status of the payment. */
  status: string;
}

export const paymentDeleteSchema: Schema<PaymentDelete> = object({
  status: ['Status', string()],
});
