/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { PaymentService, paymentServiceSchema } from './paymentService.js';

export interface PaymentServices {
  paymentServices?: PaymentService[];
}

export const paymentServicesSchema: Schema<PaymentServices> = lazy(() =>
  object({
    paymentServices: ['PaymentServices', optional(array(paymentServiceSchema))],
  })
);
