/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { Payment, paymentSchema } from './payment.js';

export interface Payments {
  payments?: Payment[];
}

export const paymentsSchema: Schema<Payments> = lazy(() =>
  object({ payments: ['Payments', optional(array(paymentSchema))] })
);
