/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PhoneTypeEnum
 */
export enum PhoneTypeEnum {
  DEFAULT = 'DEFAULT',
  DDI = 'DDI',
  MOBILE = 'MOBILE',
  FAX = 'FAX',
  OFFICE = 'OFFICE',
}

/**
 * Schema for PhoneTypeEnum
 */
export const phoneTypeEnumSchema: Schema<PhoneTypeEnum> = stringEnum(
  PhoneTypeEnum
);
