/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import { PhoneTypeEnum, phoneTypeEnumSchema } from './phoneTypeEnum.js';

export interface Phone {
  /** max length = 10 */
  phoneAreaCode?: string;
  /** max length = 20 */
  phoneCountryCode?: string;
  /** max length = 50 */
  phoneNumber?: string;
  phoneType?: PhoneTypeEnum;
}

export const phoneSchema: Schema<Phone> = object({
  phoneAreaCode: ['PhoneAreaCode', optional(string())],
  phoneCountryCode: ['PhoneCountryCode', optional(string())],
  phoneNumber: ['PhoneNumber', optional(string())],
  phoneType: ['PhoneType', optional(phoneTypeEnumSchema)],
});
