/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { Allocation, allocationSchema } from './allocation.js';
import { Attachment, attachmentSchema } from './attachment.js';
import { Contact, contactSchema } from './contact.js';
import {
  CurrencyCodeEnum,
  currencyCodeEnumSchema,
} from './currencyCodeEnum.js';
import {
  LineAmountTypesEnum,
  lineAmountTypesEnumSchema,
} from './lineAmountTypesEnum.js';
import { LineItem, lineItemSchema } from './lineItem.js';
import { Status4Enum, status4EnumSchema } from './status4Enum.js';
import { Type2Enum, type2EnumSchema } from './type2Enum.js';

export interface Prepayment {
  /** See Allocations */
  allocations?: Allocation[];
  /** The amount of applied to an invoice */
  appliedAmount?: number;
  /** See Attachments */
  attachments?: Attachment[];
  contact?: Contact;
  /** 3 letter alpha code for the currency – see list of currency codes */
  currencyCode?: CurrencyCodeEnum;
  /** The currency rate for a multicurrency prepayment. If no rate is specified, the XE.com day rate is used */
  currencyRate?: number;
  /** The date the prepayment is created YYYY-MM-DD */
  date?: string;
  /** boolean to indicate if a prepayment has an attachment */
  hasAttachments?: boolean;
  /** Line amounts are exclusive of tax by default if you don’t specify this element. See Line Amount Types */
  lineAmountTypes?: LineAmountTypesEnum;
  /** See Prepayment Line Items */
  lineItems?: LineItem[];
  /** Xero generated unique identifier */
  prepaymentID?: string;
  /** Returns Invoice number field. Reference field isn't available. */
  reference?: string;
  /** The remaining credit balance on the prepayment */
  remainingCredit?: number;
  /** See Prepayment Status Codes */
  status?: Status4Enum;
  /** The subtotal of the prepayment excluding taxes */
  subTotal?: number;
  /** The total of the prepayment(subtotal + total tax) */
  total?: number;
  /** The total tax on the prepayment */
  totalTax?: number;
  /** See Prepayment Types */
  type?: Type2Enum;
  /** UTC timestamp of last update to the prepayment */
  updatedDateUTC?: string;
}

export const prepaymentSchema: Schema<Prepayment> = lazy(() =>
  object({
    allocations: ['Allocations', optional(array(allocationSchema))],
    appliedAmount: ['AppliedAmount', optional(number())],
    attachments: ['Attachments', optional(array(attachmentSchema))],
    contact: ['Contact', optional(contactSchema)],
    currencyCode: ['CurrencyCode', optional(currencyCodeEnumSchema)],
    currencyRate: ['CurrencyRate', optional(number())],
    date: ['Date', optional(string())],
    hasAttachments: ['HasAttachments', optional(boolean())],
    lineAmountTypes: ['LineAmountTypes', optional(lineAmountTypesEnumSchema)],
    lineItems: ['LineItems', optional(array(lineItemSchema))],
    prepaymentID: ['PrepaymentID', optional(string())],
    reference: ['Reference', optional(string())],
    remainingCredit: ['RemainingCredit', optional(number())],
    status: ['Status', optional(status4EnumSchema)],
    subTotal: ['SubTotal', optional(number())],
    total: ['Total', optional(number())],
    totalTax: ['TotalTax', optional(number())],
    type: ['Type', optional(type2EnumSchema)],
    updatedDateUTC: ['UpdatedDateUTC', optional(string())],
  })
);
