/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { Prepayment, prepaymentSchema } from './prepayment.js';

export interface Prepayments {
  prepayments?: Prepayment[];
}

export const prepaymentsSchema: Schema<Prepayments> = lazy(() =>
  object({ prepayments: ['Prepayments', optional(array(prepaymentSchema))] })
);
