/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { Attachment, attachmentSchema } from './attachment.js';
import { Contact, contactSchema } from './contact.js';
import {
  CurrencyCodeEnum,
  currencyCodeEnumSchema,
} from './currencyCodeEnum.js';
import {
  LineAmountTypesEnum,
  lineAmountTypesEnumSchema,
} from './lineAmountTypesEnum.js';
import { LineItem, lineItemSchema } from './lineItem.js';
import { Status17Enum, status17EnumSchema } from './status17Enum.js';
import { ValidationError, validationErrorSchema } from './validationError.js';

export interface PurchaseOrder {
  /** Displays array of attachments from the API */
  attachments?: Attachment[];
  /** The person that the delivery is going to */
  attentionTo?: string;
  /** See BrandingThemes */
  brandingThemeID?: string;
  contact?: Contact;
  /** 3 letter alpha code for the currency – see list of currency codes */
  currencyCode?: CurrencyCodeEnum;
  /** The currency rate for a multicurrency purchase order. If no rate is specified, the XE.com day rate is used. */
  currencyRate?: number;
  /** Date purchase order was issued – YYYY-MM-DD. If the Date element is not specified then it will default to the current date based on the timezone setting of the organisation */
  date?: string;
  /** The address the goods are to be delivered to */
  deliveryAddress?: string;
  /** Date the goods are to be delivered – YYYY-MM-DD */
  deliveryDate?: string;
  /** A free text feild for instructions (500 characters max) */
  deliveryInstructions?: string;
  /** The date the goods are expected to arrive. */
  expectedArrivalDate?: string;
  /** boolean to indicate if a purchase order has an attachment */
  hasAttachments?: boolean;
  /** Line amounts are exclusive of tax by default if you don’t specify this element. See Line Amount Types */
  lineAmountTypes?: LineAmountTypesEnum;
  /** See LineItems */
  lineItems?: LineItem[];
  /** Xero generated unique identifier for purchase order */
  purchaseOrderID?: string;
  /** Unique alpha numeric code identifying purchase order (when missing will auto-generate from your Organisation Invoice Settings) */
  purchaseOrderNumber?: string;
  /** Additional reference number */
  reference?: string;
  /** Boolean to set whether the purchase order should be marked as “sent”. This can be set only on purchase orders that have been approved or billed */
  sentToContact?: boolean;
  /** See Purchase Order Status Codes */
  status?: Status17Enum;
  /** A string to indicate if a invoice status */
  statusAttributeString?: string;
  /** Total of purchase order excluding taxes */
  subTotal?: number;
  /** The phone number for the person accepting the delivery */
  telephone?: string;
  /** Total of Purchase Order tax inclusive (i.e. SubTotal + TotalTax) */
  total?: number;
  /** Total of discounts applied on the purchase order line items */
  totalDiscount?: number;
  /** Total tax on purchase order */
  totalTax?: number;
  /** Last modified date UTC format */
  updatedDateUTC?: string;
  /** Displays array of validation error messages from the API */
  validationErrors?: ValidationError[];
  /** Displays array of warning messages from the API */
  warnings?: ValidationError[];
}

export const purchaseOrderSchema: Schema<PurchaseOrder> = lazy(() =>
  object({
    attachments: ['Attachments', optional(array(attachmentSchema))],
    attentionTo: ['AttentionTo', optional(string())],
    brandingThemeID: ['BrandingThemeID', optional(string())],
    contact: ['Contact', optional(contactSchema)],
    currencyCode: ['CurrencyCode', optional(currencyCodeEnumSchema)],
    currencyRate: ['CurrencyRate', optional(number())],
    date: ['Date', optional(string())],
    deliveryAddress: ['DeliveryAddress', optional(string())],
    deliveryDate: ['DeliveryDate', optional(string())],
    deliveryInstructions: ['DeliveryInstructions', optional(string())],
    expectedArrivalDate: ['ExpectedArrivalDate', optional(string())],
    hasAttachments: ['HasAttachments', optional(boolean())],
    lineAmountTypes: ['LineAmountTypes', optional(lineAmountTypesEnumSchema)],
    lineItems: ['LineItems', optional(array(lineItemSchema))],
    purchaseOrderID: ['PurchaseOrderID', optional(string())],
    purchaseOrderNumber: ['PurchaseOrderNumber', optional(string())],
    reference: ['Reference', optional(string())],
    sentToContact: ['SentToContact', optional(boolean())],
    status: ['Status', optional(status17EnumSchema)],
    statusAttributeString: ['StatusAttributeString', optional(string())],
    subTotal: ['SubTotal', optional(number())],
    telephone: ['Telephone', optional(string())],
    total: ['Total', optional(number())],
    totalDiscount: ['TotalDiscount', optional(number())],
    totalTax: ['TotalTax', optional(number())],
    updatedDateUTC: ['UpdatedDateUTC', optional(string())],
    validationErrors: [
      'ValidationErrors',
      optional(array(validationErrorSchema)),
    ],
    warnings: ['Warnings', optional(array(validationErrorSchema))],
  })
);
