/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { PurchaseOrder, purchaseOrderSchema } from './purchaseOrder.js';

export interface PurchaseOrders {
  purchaseOrders?: PurchaseOrder[];
}

export const purchaseOrdersSchema: Schema<PurchaseOrders> = lazy(() =>
  object({
    purchaseOrders: ['PurchaseOrders', optional(array(purchaseOrderSchema))],
  })
);
