/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema.js';

export interface Purchase {
  /** Default account code to be used for purchased/sale. Not applicable to the purchase details of tracked items */
  accountCode?: string;
  /** Cost of goods sold account. Only applicable to the purchase details of tracked items. */
  cOGSAccountCode?: string;
  /** The tax type from TaxRates */
  taxType?: string;
  /** Unit Price of the item. By default UnitPrice is rounded to two decimal places. You can use 4 decimal places by adding the unitdp=4 querystring parameter to your request. */
  unitPrice?: number;
}

export const purchaseSchema: Schema<Purchase> = object({
  accountCode: ['AccountCode', optional(string())],
  cOGSAccountCode: ['COGSAccountCode', optional(string())],
  taxType: ['TaxType', optional(string())],
  unitPrice: ['UnitPrice', optional(number())],
});
