/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for QuoteLineAmountTypesEnum
 */
export enum QuoteLineAmountTypesEnum {
  EXCLUSIVE = 'EXCLUSIVE',
  INCLUSIVE = 'INCLUSIVE',
  NOTAX = 'NOTAX',
}

/**
 * Schema for QuoteLineAmountTypesEnum
 */
export const quoteLineAmountTypesEnumSchema: Schema<QuoteLineAmountTypesEnum> = stringEnum(
  QuoteLineAmountTypesEnum
);
