/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for QuoteStatusCodesEnum
 */
export enum QuoteStatusCodesEnum {
  DRAFT = 'DRAFT',
  SENT = 'SENT',
  DECLINED = 'DECLINED',
  ACCEPTED = 'ACCEPTED',
  INVOICED = 'INVOICED',
  DELETED = 'DELETED',
}

/**
 * Schema for QuoteStatusCodesEnum
 */
export const quoteStatusCodesEnumSchema: Schema<QuoteStatusCodesEnum> = stringEnum(
  QuoteStatusCodesEnum
);
