/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { Contact, contactSchema } from './contact.js';
import {
  CurrencyCodeEnum,
  currencyCodeEnumSchema,
} from './currencyCodeEnum.js';
import { LineItem, lineItemSchema } from './lineItem.js';
import {
  QuoteLineAmountTypesEnum,
  quoteLineAmountTypesEnumSchema,
} from './quoteLineAmountTypesEnum.js';
import {
  QuoteStatusCodesEnum,
  quoteStatusCodesEnumSchema,
} from './quoteStatusCodesEnum.js';
import { ValidationError, validationErrorSchema } from './validationError.js';

export interface Quote {
  /** See BrandingThemes */
  brandingThemeID?: string;
  contact?: Contact;
  /** 3 letter alpha code for the currency – see list of currency codes */
  currencyCode?: CurrencyCodeEnum;
  /** The currency rate for a multicurrency quote */
  currencyRate?: number;
  /** Date quote was issued – YYYY-MM-DD. If the Date element is not specified it will default to the current date based on the timezone setting of the organisation */
  date?: string;
  /** Date the quote was issued (YYYY-MM-DD) */
  dateString?: string;
  /** Date the quote expires – YYYY-MM-DD. */
  expiryDate?: string;
  /** Date the quote expires – YYYY-MM-DD. */
  expiryDateString?: string;
  /** Line amounts are exclusive of tax by default if you don’t specify this element. See Line Amount Types */
  lineAmountTypes?: QuoteLineAmountTypesEnum;
  /** See LineItems */
  lineItems?: LineItem[];
  /** QuoteID GUID is automatically generated and is returned after create or GET. */
  quoteID?: string;
  /** Unique alpha numeric code identifying a quote (Max Length = 255) */
  quoteNumber?: string;
  /** Additional reference number */
  reference?: string;
  /** The status of the quote. */
  status?: QuoteStatusCodesEnum;
  /** A string to indicate if a invoice status */
  statusAttributeString?: string;
  /** Total of quote excluding taxes. */
  subTotal?: number;
  /** Summary text for the quote */
  summary?: string;
  /** Terms of the quote */
  terms?: string;
  /** Title text for the quote */
  title?: string;
  /** Total of Quote tax inclusive (i.e. SubTotal + TotalTax). This will be ignored if it doesn’t equal the sum of the LineAmounts */
  total?: number;
  /** Total of discounts applied on the quote line items */
  totalDiscount?: number;
  /** Total tax on quote */
  totalTax?: number;
  /** Last modified date UTC format */
  updatedDateUTC?: string;
  /** Displays array of validation error messages from the API */
  validationErrors?: ValidationError[];
}

export const quoteSchema: Schema<Quote> = lazy(() =>
  object({
    brandingThemeID: ['BrandingThemeID', optional(string())],
    contact: ['Contact', optional(contactSchema)],
    currencyCode: ['CurrencyCode', optional(currencyCodeEnumSchema)],
    currencyRate: ['CurrencyRate', optional(number())],
    date: ['Date', optional(string())],
    dateString: ['DateString', optional(string())],
    expiryDate: ['ExpiryDate', optional(string())],
    expiryDateString: ['ExpiryDateString', optional(string())],
    lineAmountTypes: [
      'LineAmountTypes',
      optional(quoteLineAmountTypesEnumSchema),
    ],
    lineItems: ['LineItems', optional(array(lineItemSchema))],
    quoteID: ['QuoteID', optional(string())],
    quoteNumber: ['QuoteNumber', optional(string())],
    reference: ['Reference', optional(string())],
    status: ['Status', optional(quoteStatusCodesEnumSchema)],
    statusAttributeString: ['StatusAttributeString', optional(string())],
    subTotal: ['SubTotal', optional(number())],
    summary: ['Summary', optional(string())],
    terms: ['Terms', optional(string())],
    title: ['Title', optional(string())],
    total: ['Total', optional(number())],
    totalDiscount: ['TotalDiscount', optional(number())],
    totalTax: ['TotalTax', optional(number())],
    updatedDateUTC: ['UpdatedDateUTC', optional(string())],
    validationErrors: [
      'ValidationErrors',
      optional(array(validationErrorSchema)),
    ],
  })
);
