/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { Quote, quoteSchema } from './quote.js';

export interface Quotes {
  quotes?: Quote[];
}

export const quotesSchema: Schema<Quotes> = lazy(() =>
  object({ quotes: ['Quotes', optional(array(quoteSchema))] })
);
