/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { Attachment, attachmentSchema } from './attachment.js';
import { Contact, contactSchema } from './contact.js';
import {
  LineAmountTypesEnum,
  lineAmountTypesEnumSchema,
} from './lineAmountTypesEnum.js';
import { LineItem, lineItemSchema } from './lineItem.js';
import { Status11Enum, status11EnumSchema } from './status11Enum.js';
import { User, userSchema } from './user.js';
import { ValidationError, validationErrorSchema } from './validationError.js';

export interface Receipt {
  /** Displays array of attachments from the API */
  attachments?: Attachment[];
  contact?: Contact;
  /** Date of receipt – YYYY-MM-DD */
  date?: string;
  /** boolean to indicate if a receipt has an attachment */
  hasAttachments?: boolean;
  /** Line amounts are exclusive of tax by default if you don’t specify this element. See Line Amount Types */
  lineAmountTypes?: LineAmountTypesEnum;
  lineItems?: LineItem[];
  /** Xero generated unique identifier for receipt */
  receiptID?: string;
  /** Xero generated sequence number for receipt in current claim for a given user */
  receiptNumber?: string;
  /** Additional reference number */
  reference?: string;
  /** Current status of receipt – see status types */
  status?: Status11Enum;
  /** Total of receipt excluding taxes */
  subTotal?: number;
  /** Total of receipt tax inclusive (i.e. SubTotal + TotalTax) */
  total?: number;
  /** Total tax on receipt */
  totalTax?: number;
  /** Last modified date UTC format */
  updatedDateUTC?: string;
  /** URL link to a source document – shown as “Go to [appName]” in the Xero app */
  url?: string;
  user?: User;
  /** Displays array of validation error messages from the API */
  validationErrors?: ValidationError[];
  /** Displays array of warning messages from the API */
  warnings?: ValidationError[];
}

export const receiptSchema: Schema<Receipt> = lazy(() =>
  object({
    attachments: ['Attachments', optional(array(attachmentSchema))],
    contact: ['Contact', optional(contactSchema)],
    date: ['Date', optional(string())],
    hasAttachments: ['HasAttachments', optional(boolean())],
    lineAmountTypes: ['LineAmountTypes', optional(lineAmountTypesEnumSchema)],
    lineItems: ['LineItems', optional(array(lineItemSchema))],
    receiptID: ['ReceiptID', optional(string())],
    receiptNumber: ['ReceiptNumber', optional(string())],
    reference: ['Reference', optional(string())],
    status: ['Status', optional(status11EnumSchema)],
    subTotal: ['SubTotal', optional(number())],
    total: ['Total', optional(number())],
    totalTax: ['TotalTax', optional(number())],
    updatedDateUTC: ['UpdatedDateUTC', optional(string())],
    url: ['Url', optional(string())],
    user: ['User', optional(userSchema)],
    validationErrors: [
      'ValidationErrors',
      optional(array(validationErrorSchema)),
    ],
    warnings: ['Warnings', optional(array(validationErrorSchema))],
  })
);
