/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { Receipt, receiptSchema } from './receipt.js';

export interface Receipts {
  receipts?: Receipt[];
}

export const receiptsSchema: Schema<Receipts> = lazy(() =>
  object({ receipts: ['Receipts', optional(array(receiptSchema))] })
);
