/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import {
  RepeatingInvoice,
  repeatingInvoiceSchema,
} from './repeatingInvoice.js';

export interface RepeatingInvoices {
  repeatingInvoices?: RepeatingInvoice[];
}

export const repeatingInvoicesSchema: Schema<RepeatingInvoices> = lazy(() =>
  object({
    repeatingInvoices: [
      'RepeatingInvoices',
      optional(array(repeatingInvoiceSchema)),
    ],
  })
);
