/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { Attachment, attachmentSchema } from './attachment.js';
import { Contact, contactSchema } from './contact.js';
import {
  CurrencyCodeEnum,
  currencyCodeEnumSchema,
} from './currencyCodeEnum.js';
import {
  LineAmountTypesEnum,
  lineAmountTypesEnumSchema,
} from './lineAmountTypesEnum.js';
import { LineItem, lineItemSchema } from './lineItem.js';
import { Schedule, scheduleSchema } from './schedule.js';
import { Status18Enum, status18EnumSchema } from './status18Enum.js';
import { Type8Enum, type8EnumSchema } from './type8Enum.js';

export interface RepeatingInvoice {
  /** Displays array of attachments from the API */
  attachments?: Attachment[];
  /** See BrandingThemes */
  brandingThemeID?: string;
  contact?: Contact;
  /** 3 letter alpha code for the currency – see list of currency codes */
  currencyCode?: CurrencyCodeEnum;
  /** boolean to indicate if an invoice has an attachment */
  hasAttachments?: boolean;
  /** Xero generated unique identifier for repeating invoice template */
  iD?: string;
  /** Line amounts are exclusive of tax by default if you don’t specify this element. See Line Amount Types */
  lineAmountTypes?: LineAmountTypesEnum;
  /** See LineItems */
  lineItems?: LineItem[];
  /** ACCREC only – additional reference number */
  reference?: string;
  /** Xero generated unique identifier for repeating invoice template */
  repeatingInvoiceID?: string;
  schedule?: Schedule;
  /** One of the following - DRAFT or AUTHORISED – See Invoice Status Codes */
  status?: Status18Enum;
  /** Total of invoice excluding taxes */
  subTotal?: number;
  /** Total of Invoice tax inclusive (i.e. SubTotal + TotalTax) */
  total?: number;
  /** Total tax on invoice */
  totalTax?: number;
  /** See Invoice Types */
  type?: Type8Enum;
}

export const repeatingInvoiceSchema: Schema<RepeatingInvoice> = lazy(() =>
  object({
    attachments: ['Attachments', optional(array(attachmentSchema))],
    brandingThemeID: ['BrandingThemeID', optional(string())],
    contact: ['Contact', optional(contactSchema)],
    currencyCode: ['CurrencyCode', optional(currencyCodeEnumSchema)],
    hasAttachments: ['HasAttachments', optional(boolean())],
    iD: ['ID', optional(string())],
    lineAmountTypes: ['LineAmountTypes', optional(lineAmountTypesEnumSchema)],
    lineItems: ['LineItems', optional(array(lineItemSchema))],
    reference: ['Reference', optional(string())],
    repeatingInvoiceID: ['RepeatingInvoiceID', optional(string())],
    schedule: ['Schedule', optional(scheduleSchema)],
    status: ['Status', optional(status18EnumSchema)],
    subTotal: ['SubTotal', optional(number())],
    total: ['Total', optional(number())],
    totalTax: ['TotalTax', optional(number())],
    type: ['Type', optional(type8EnumSchema)],
  })
);
