/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { Report, reportSchema } from './report.js';

export interface Reports {
  reports?: Report[];
}

export const reportsSchema: Schema<Reports> = lazy(() =>
  object({ reports: ['Reports', optional(array(reportSchema))] })
);
