/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import { ReportTypeEnum, reportTypeEnumSchema } from './reportTypeEnum.js';
import {
  TenNinetyNineContact,
  tenNinetyNineContactSchema,
} from './tenNinetyNineContact.js';

export interface Report {
  contacts?: TenNinetyNineContact[];
  /** Date of report */
  reportDate?: string;
  /** See Prepayment Types */
  reportID?: string;
  /** See Prepayment Types */
  reportName?: string;
  /** See Prepayment Types */
  reportTitle?: string;
  /** See Prepayment Types */
  reportType?: ReportTypeEnum;
  /** Updated Date */
  updatedDateUTC?: string;
}

export const reportSchema: Schema<Report> = lazy(() =>
  object({
    contacts: ['Contacts', optional(array(tenNinetyNineContactSchema))],
    reportDate: ['ReportDate', optional(string())],
    reportID: ['ReportID', optional(string())],
    reportName: ['ReportName', optional(string())],
    reportTitle: ['ReportTitle', optional(string())],
    reportType: ['ReportType', optional(reportTypeEnumSchema)],
    updatedDateUTC: ['UpdatedDateUTC', optional(string())],
  })
);
