/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import { ReportCell, reportCellSchema } from './reportCell.js';
import { ReportRow, reportRowSchema } from './reportRow.js';
import { RowTypeEnum, rowTypeEnumSchema } from './rowTypeEnum.js';

export interface ReportRows {
  cells?: ReportCell[];
  rowType?: RowTypeEnum;
  rows?: ReportRow[];
  title?: string;
}

export const reportRowsSchema: Schema<ReportRows> = lazy(() =>
  object({
    cells: ['Cells', optional(array(reportCellSchema))],
    rowType: ['RowType', optional(rowTypeEnumSchema)],
    rows: ['Rows', optional(array(reportRowSchema))],
    title: ['Title', optional(string())],
  })
);
