/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import { ReportAttribute, reportAttributeSchema } from './reportAttribute.js';

export interface ReportCell {
  attributes?: ReportAttribute[];
  value?: string;
}

export const reportCellSchema: Schema<ReportCell> = lazy(() =>
  object({
    attributes: ['Attributes', optional(array(reportAttributeSchema))],
    value: ['Value', optional(string())],
  })
);
