/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface ReportAttribute {
  id?: string;
  value?: string;
}

export const reportAttributeSchema: Schema<ReportAttribute> = object({
  id: ['Id', optional(string())],
  value: ['Value', optional(string())],
});
