/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import { ReportFields, reportFieldsSchema } from './reportFields.js';
import { ReportRows, reportRowsSchema } from './reportRows.js';

export interface ReportWithRow {
  fields?: ReportFields[];
  /** Date of report */
  reportDate?: string;
  /** Report id */
  reportID?: string;
  /** Name of the report */
  reportName?: string;
  /** Title of the report */
  reportTitle?: string;
  /** Report titles array (3 to 4 strings with the report name, orgnisation name and time frame of report) */
  reportTitles?: string[];
  /** The type of report (BalanceSheet,ProfitLoss, etc) */
  reportType?: string;
  rows?: ReportRows[];
  /** Updated Date */
  updatedDateUTC?: string;
}

export const reportWithRowSchema: Schema<ReportWithRow> = lazy(() =>
  object({
    fields: ['Fields', optional(array(reportFieldsSchema))],
    reportDate: ['ReportDate', optional(string())],
    reportID: ['ReportID', optional(string())],
    reportName: ['ReportName', optional(string())],
    reportTitle: ['ReportTitle', optional(string())],
    reportTitles: ['ReportTitles', optional(array(string()))],
    reportType: ['ReportType', optional(string())],
    rows: ['Rows', optional(array(reportRowsSchema))],
    updatedDateUTC: ['UpdatedDateUTC', optional(string())],
  })
);
