/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import { ReportCell, reportCellSchema } from './reportCell.js';
import { RowTypeEnum, rowTypeEnumSchema } from './rowTypeEnum.js';

export interface ReportRow {
  cells?: ReportCell[];
  rowType?: RowTypeEnum;
  title?: string;
}

export const reportRowSchema: Schema<ReportRow> = lazy(() =>
  object({
    cells: ['Cells', optional(array(reportCellSchema))],
    rowType: ['RowType', optional(rowTypeEnumSchema)],
    title: ['Title', optional(string())],
  })
);
