/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface ReportFields {
  description?: string;
  fieldID?: string;
  value?: string;
}

export const reportFieldsSchema: Schema<ReportFields> = object({
  description: ['Description', optional(string())],
  fieldID: ['FieldID', optional(string())],
  value: ['Value', optional(string())],
});
