/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ReportTypeEnum
 */
export enum ReportTypeEnum {
  AgedPayablesByContact = 'AgedPayablesByContact',
}

/**
 * Schema for ReportTypeEnum
 */
export const reportTypeEnumSchema: Schema<ReportTypeEnum> = stringEnum(
  ReportTypeEnum
);
