/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { ReportWithRow, reportWithRowSchema } from './reportWithRow.js';

export interface ReportWithRows {
  reports?: ReportWithRow[];
}

export const reportWithRowsSchema: Schema<ReportWithRows> = lazy(() =>
  object({ reports: ['Reports', optional(array(reportWithRowSchema))] })
);
