/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface RequestEmpty {
  /** Need at least one field to create an empty JSON payload */
  status?: string;
}

export const requestEmptySchema: Schema<RequestEmpty> = object({
  status: ['Status', optional(string())],
});
