/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for RowTypeEnum
 */
export enum RowTypeEnum {
  Header = 'Header',
  Section = 'Section',
  Row = 'Row',
  SummaryRow = 'SummaryRow',
}

/**
 * Schema for RowTypeEnum
 */
export const rowTypeEnumSchema: Schema<RowTypeEnum> = stringEnum(RowTypeEnum);
