/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface SalesTrackingCategory {
  /** The default sales tracking category name for contacts */
  trackingCategoryName?: string;
  /** The default purchase tracking category name for contacts */
  trackingOptionName?: string;
}

export const salesTrackingCategorySchema: Schema<SalesTrackingCategory> = object(
  {
    trackingCategoryName: ['TrackingCategoryName', optional(string())],
    trackingOptionName: ['TrackingOptionName', optional(string())],
  }
);
