/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for SalesTaxPeriodEnum
 */
export enum SalesTaxPeriodEnum {
  MONTHLY = 'MONTHLY',
  QUARTERLY1 = 'QUARTERLY1',
  QUARTERLY2 = 'QUARTERLY2',
  QUARTERLY3 = 'QUARTERLY3',
  ANNUALLY = 'ANNUALLY',
  ONEMONTHS = 'ONEMONTHS',
  TWOMONTHS = 'TWOMONTHS',
  SIXMONTHS = 'SIXMONTHS',
  Enum1MONTHLY = '1MONTHLY',
  Enum2MONTHLY = '2MONTHLY',
  Enum3MONTHLY = '3MONTHLY',
  Enum6MONTHLY = '6MONTHLY',
  QUARTERLY = 'QUARTERLY',
  YEARLY = 'YEARLY',
  NONE = 'NONE',
}

/**
 * Schema for SalesTaxPeriodEnum
 */
export const salesTaxPeriodEnumSchema: Schema<SalesTaxPeriodEnum> = stringEnum(
  SalesTaxPeriodEnum
);
