/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for SalesTaxBasisEnum
 */
export enum SalesTaxBasisEnum {
  PAYMENTS = 'PAYMENTS',
  INVOICE = 'INVOICE',
  NONE = 'NONE',
  CASH = 'CASH',
  ACCRUAL = 'ACCRUAL',
  FLATRATECASH = 'FLATRATECASH',
  FLATRATEACCRUAL = 'FLATRATEACCRUAL',
  ACCRUALS = 'ACCRUALS',
}

/**
 * Schema for SalesTaxBasisEnum
 */
export const salesTaxBasisEnumSchema: Schema<SalesTaxBasisEnum> = stringEnum(
  SalesTaxBasisEnum
);
