/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema.js';
import { DueDateTypeEnum, dueDateTypeEnumSchema } from './dueDateTypeEnum.js';
import { UnitEnum, unitEnumSchema } from './unitEnum.js';

export interface Schedule {
  /** Integer used with due date type e.g 20 (of following month), 31 (of current month) */
  dueDate?: number;
  /** the payment terms */
  dueDateType?: DueDateTypeEnum;
  /** Invoice end date – only returned if the template has an end date set */
  endDate?: string;
  /** The calendar date of the next invoice in the schedule to be generated */
  nextScheduledDate?: string;
  /** Integer used with the unit e.g. 1 (every 1 week), 2 (every 2 months) */
  period?: number;
  /** Date the first invoice of the current version of the repeating schedule was generated (changes when repeating invoice is edited) */
  startDate?: string;
  /** One of the following - WEEKLY or MONTHLY */
  unit?: UnitEnum;
}

export const scheduleSchema: Schema<Schedule> = object({
  dueDate: ['DueDate', optional(number())],
  dueDateType: ['DueDateType', optional(dueDateTypeEnumSchema)],
  endDate: ['EndDate', optional(string())],
  nextScheduledDate: ['NextScheduledDate', optional(string())],
  period: ['Period', optional(number())],
  startDate: ['StartDate', optional(string())],
  unit: ['Unit', optional(unitEnumSchema)],
});
