/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { Account, accountSchema } from './account.js';
import {
  ConversionBalances,
  conversionBalancesSchema,
} from './conversionBalances.js';
import { ConversionDate, conversionDateSchema } from './conversionDate.js';

export interface Setup {
  accounts?: Account[];
  /** Balance supplied for each account that has a value as at the conversion date. */
  conversionBalances?: ConversionBalances[];
  /** The date when the organisation starts using Xero */
  conversionDate?: ConversionDate;
}

export const setupSchema: Schema<Setup> = lazy(() =>
  object({
    accounts: ['Accounts', optional(array(accountSchema))],
    conversionBalances: [
      'ConversionBalances',
      optional(array(conversionBalancesSchema)),
    ],
    conversionDate: ['ConversionDate', optional(conversionDateSchema)],
  })
);
