/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for SourceTransactionTypeCodeEnum
 */
export enum SourceTransactionTypeCodeEnum {
  ACCPAY = 'ACCPAY',
  SPEND = 'SPEND',
}

/**
 * Schema for SourceTransactionTypeCodeEnum
 */
export const sourceTransactionTypeCodeEnumSchema: Schema<SourceTransactionTypeCodeEnum> = stringEnum(
  SourceTransactionTypeCodeEnum
);
