/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status11Enum
 */
export enum Status11Enum {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  AUTHORISED = 'AUTHORISED',
  DECLINED = 'DECLINED',
  VOIDED = 'VOIDED',
}

/**
 * Schema for Status11Enum
 */
export const status11EnumSchema: Schema<Status11Enum> = stringEnum(
  Status11Enum
);
