/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status18Enum
 */
export enum Status18Enum {
  DRAFT = 'DRAFT',
  AUTHORISED = 'AUTHORISED',
  DELETED = 'DELETED',
}

/**
 * Schema for Status18Enum
 */
export const status18EnumSchema: Schema<Status18Enum> = stringEnum(
  Status18Enum
);
