/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status4Enum
 */
export enum Status4Enum {
  AUTHORISED = 'AUTHORISED',
  PAID = 'PAID',
  VOIDED = 'VOIDED',
}

/**
 * Schema for Status4Enum
 */
export const status4EnumSchema: Schema<Status4Enum> = stringEnum(Status4Enum);
