/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status20Enum
 */
export enum Status20Enum {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  AUTHORISED = 'AUTHORISED',
  BILLED = 'BILLED',
  DELETED = 'DELETED',
}

/**
 * Schema for Status20Enum
 */
export const status20EnumSchema: Schema<Status20Enum> = stringEnum(
  Status20Enum
);
