/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status16Enum
 */
export enum Status16Enum {
  DRAFT = 'DRAFT',
  POSTED = 'POSTED',
  DELETED = 'DELETED',
  VOIDED = 'VOIDED',
  ARCHIVED = 'ARCHIVED',
}

/**
 * Schema for Status16Enum
 */
export const status16EnumSchema: Schema<Status16Enum> = stringEnum(
  Status16Enum
);
