/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status10Enum
 */
export enum Status10Enum {
  ACTIVE = 'ACTIVE',
  ARCHIVED = 'ARCHIVED',
  GDPRREQUEST = 'GDPRREQUEST',
  DELETED = 'DELETED',
}

/**
 * Schema for Status10Enum
 */
export const status10EnumSchema: Schema<Status10Enum> = stringEnum(
  Status10Enum
);
