/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status13Enum
 */
export enum Status13Enum {
  ACTIVE = 'ACTIVE',
  ARCHIVED = 'ARCHIVED',
  DELETED = 'DELETED',
}

/**
 * Schema for Status13Enum
 */
export const status13EnumSchema: Schema<Status13Enum> = stringEnum(
  Status13Enum
);
