/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status6Enum
 */
export enum Status6Enum {
  AUTHORISED = 'AUTHORISED',
  DELETED = 'DELETED',
}

/**
 * Schema for Status6Enum
 */
export const status6EnumSchema: Schema<Status6Enum> = stringEnum(Status6Enum);
