/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status17Enum
 */
export enum Status17Enum {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  AUTHORISED = 'AUTHORISED',
  BILLED = 'BILLED',
  DELETED = 'DELETED',
}

/**
 * Schema for Status17Enum
 */
export const status17EnumSchema: Schema<Status17Enum> = stringEnum(
  Status17Enum
);
