/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status12Enum
 */
export enum Status12Enum {
  SUBMITTED = 'SUBMITTED',
  AUTHORISED = 'AUTHORISED',
  PAID = 'PAID',
  VOIDED = 'VOIDED',
  DELETED = 'DELETED',
}

/**
 * Schema for Status12Enum
 */
export const status12EnumSchema: Schema<Status12Enum> = stringEnum(
  Status12Enum
);
