/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status14Enum
 */
export enum Status14Enum {
  ACTIVE = 'ACTIVE',
  ARCHIVED = 'ARCHIVED',
  DELETED = 'DELETED',
}

/**
 * Schema for Status14Enum
 */
export const status14EnumSchema: Schema<Status14Enum> = stringEnum(
  Status14Enum
);
