/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status19Enum
 */
export enum Status19Enum {
  ACTIVE = 'ACTIVE',
  DELETED = 'DELETED',
  ARCHIVED = 'ARCHIVED',
  PENDING = 'PENDING',
}

/**
 * Schema for Status19Enum
 */
export const status19EnumSchema: Schema<Status19Enum> = stringEnum(
  Status19Enum
);
