/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';

export interface TaxComponent {
  /** Boolean to describe if Tax rate is compounded. */
  isCompound?: boolean;
  /** Boolean to describe if tax rate is non-recoverable. Non-recoverable rates are only applicable to Canadian organisations */
  isNonRecoverable?: boolean;
  /** Name of Tax Component */
  name?: string;
  /** Tax Rate (up to 4dp) */
  rate?: number;
}

export const taxComponentSchema: Schema<TaxComponent> = object({
  isCompound: ['IsCompound', optional(boolean())],
  isNonRecoverable: ['IsNonRecoverable', optional(boolean())],
  name: ['Name', optional(string())],
  rate: ['Rate', optional(number())],
});
