/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { TaxRate, taxRateSchema } from './taxRate.js';

export interface TaxRates {
  taxRates?: TaxRate[];
}

export const taxRatesSchema: Schema<TaxRates> = lazy(() =>
  object({ taxRates: ['TaxRates', optional(array(taxRateSchema))] })
);
