/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import {
  ReportTaxTypeEnum,
  reportTaxTypeEnumSchema,
} from './reportTaxTypeEnum.js';
import { Status19Enum, status19EnumSchema } from './status19Enum.js';
import { TaxComponent, taxComponentSchema } from './taxComponent.js';

export interface TaxRate {
  /** Boolean to describe if tax rate can be used for asset accounts i.e.  true,false */
  canApplyToAssets?: boolean;
  /** Boolean to describe if tax rate can be used for equity accounts i.e true,false */
  canApplyToEquity?: boolean;
  /** Boolean to describe if tax rate can be used for expense accounts  i.e. true,false */
  canApplyToExpenses?: boolean;
  /** Boolean to describe if tax rate can be used for liability accounts  i.e. true,false */
  canApplyToLiabilities?: boolean;
  /** Boolean to describe if tax rate can be used for revenue accounts i.e. true,false */
  canApplyToRevenue?: boolean;
  /** Tax Rate (decimal to 4dp) e.g 12.5000 */
  displayTaxRate?: number;
  /** Effective Tax Rate (decimal to 4dp) e.g 12.5000 */
  effectiveRate?: number;
  /** Name of tax rate */
  name?: string;
  /** See ReportTaxTypes */
  reportTaxType?: ReportTaxTypeEnum;
  /** See Status Codes */
  status?: Status19Enum;
  /** See TaxComponents */
  taxComponents?: TaxComponent[];
  /** The tax type */
  taxType?: string;
}

export const taxRateSchema: Schema<TaxRate> = lazy(() =>
  object({
    canApplyToAssets: ['CanApplyToAssets', optional(boolean())],
    canApplyToEquity: ['CanApplyToEquity', optional(boolean())],
    canApplyToExpenses: ['CanApplyToExpenses', optional(boolean())],
    canApplyToLiabilities: ['CanApplyToLiabilities', optional(boolean())],
    canApplyToRevenue: ['CanApplyToRevenue', optional(boolean())],
    displayTaxRate: ['DisplayTaxRate', optional(number())],
    effectiveRate: ['EffectiveRate', optional(number())],
    name: ['Name', optional(string())],
    reportTaxType: ['ReportTaxType', optional(reportTaxTypeEnumSchema)],
    status: ['Status', optional(status19EnumSchema)],
    taxComponents: ['TaxComponents', optional(array(taxComponentSchema))],
    taxType: ['TaxType', optional(string())],
  })
);
