/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema.js';

export interface TenNinetyNineContact {
  /** Box 1 on 1099 Form */
  box1?: number;
  /** Box 10 on 1099 Form */
  box10?: number;
  /** Box 11 on 1099 Form */
  box11?: number;
  /** Box 13 on 1099 Form */
  box13?: number;
  /** Box 14 on 1099 Form */
  box14?: number;
  /** Box 2 on 1099 Form */
  box2?: number;
  /** Box 3 on 1099 Form */
  box3?: number;
  /** Box 4 on 1099 Form */
  box4?: number;
  /** Box 5 on 1099 Form */
  box5?: number;
  /** Box 6 on 1099 Form */
  box6?: number;
  /** Box 7 on 1099 Form */
  box7?: number;
  /** Box 8 on 1099 Form */
  box8?: number;
  /** Box 9 on 1099 Form */
  box9?: number;
  /** Contact city on 1099 Form */
  city?: string;
  /** Contact contact id */
  contactId?: string;
  /** Contact email on 1099 Form */
  email?: string;
  /** Contact Fed Tax ID type */
  federalTaxIDType?: string;
  /** Contact name on 1099 Form */
  name?: string;
  /** Contact State on 1099 Form */
  state?: string;
  /** Contact address on 1099 Form */
  streetAddress?: string;
  /** Contact tax id on 1099 Form */
  taxID?: string;
  /** Contact zip on 1099 Form */
  zip?: string;
}

export const tenNinetyNineContactSchema: Schema<TenNinetyNineContact> = object({
  box1: ['Box1', optional(number())],
  box10: ['Box10', optional(number())],
  box11: ['Box11', optional(number())],
  box13: ['Box13', optional(number())],
  box14: ['Box14', optional(number())],
  box2: ['Box2', optional(number())],
  box3: ['Box3', optional(number())],
  box4: ['Box4', optional(number())],
  box5: ['Box5', optional(number())],
  box6: ['Box6', optional(number())],
  box7: ['Box7', optional(number())],
  box8: ['Box8', optional(number())],
  box9: ['Box9', optional(number())],
  city: ['City', optional(string())],
  contactId: ['ContactId', optional(string())],
  email: ['Email', optional(string())],
  federalTaxIDType: ['FederalTaxIDType', optional(string())],
  name: ['Name', optional(string())],
  state: ['State', optional(string())],
  streetAddress: ['StreetAddress', optional(string())],
  taxID: ['TaxID', optional(string())],
  zip: ['Zip', optional(string())],
});
