/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for TimeframeEnum
 */
export enum TimeframeEnum {
  MONTH = 'MONTH',
  QUARTER = 'QUARTER',
  YEAR = 'YEAR',
}

/**
 * Schema for TimeframeEnum
 */
export const timeframeEnumSchema: Schema<TimeframeEnum> = stringEnum(
  TimeframeEnum
);
