/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import {
  TrackingCategory,
  trackingCategorySchema,
} from './trackingCategory.js';

export interface TrackingCategories {
  trackingCategories?: TrackingCategory[];
}

export const trackingCategoriesSchema: Schema<TrackingCategories> = lazy(() =>
  object({
    trackingCategories: [
      'TrackingCategories',
      optional(array(trackingCategorySchema)),
    ],
  })
);
