/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { TrackingOption, trackingOptionSchema } from './trackingOption.js';

export interface TrackingOptions {
  options?: TrackingOption[];
}

export const trackingOptionsSchema: Schema<TrackingOptions> = lazy(() =>
  object({ options: ['Options', optional(array(trackingOptionSchema))] })
);
