/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import { Status14Enum, status14EnumSchema } from './status14Enum.js';
import { TrackingOption, trackingOptionSchema } from './trackingOption.js';

export interface TrackingCategory {
  /** The name of the tracking category e.g. Department, Region (max length = 100) */
  name?: string;
  /** The option name of the tracking option e.g. East, West (max length = 100) */
  option?: string;
  /** See Tracking Options */
  options?: TrackingOption[];
  /** The status of a tracking category */
  status?: Status14Enum;
  /** The Xero identifier for a tracking category e.g. 297c2dc5-cc47-4afd-8ec8-74990b8761e9 */
  trackingCategoryID?: string;
  /** The Xero identifier for a tracking option e.g. dc54c220-0140-495a-b925-3246adc0075f */
  trackingOptionID?: string;
}

export const trackingCategorySchema: Schema<TrackingCategory> = lazy(() =>
  object({
    name: ['Name', optional(string())],
    option: ['Option', optional(string())],
    options: ['Options', optional(array(trackingOptionSchema))],
    status: ['Status', optional(status14EnumSchema)],
    trackingCategoryID: ['TrackingCategoryID', optional(string())],
    trackingOptionID: ['TrackingOptionID', optional(string())],
  })
);
