/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import { Status13Enum, status13EnumSchema } from './status13Enum.js';

export interface TrackingOption {
  /** The name of the tracking option e.g. Marketing, East (max length = 100) */
  name?: string;
  /** The status of a tracking option */
  status?: Status13Enum;
  /** Filter by a tracking category e.g. 297c2dc5-cc47-4afd-8ec8-74990b8761e9 */
  trackingCategoryID?: string;
  /** The Xero identifier for a tracking option e.g. ae777a87-5ef3-4fa0-a4f0-d10e1f13073a */
  trackingOptionID?: string;
}

export const trackingOptionSchema: Schema<TrackingOption> = object({
  name: ['Name', optional(string())],
  status: ['Status', optional(status13EnumSchema)],
  trackingCategoryID: ['TrackingCategoryID', optional(string())],
  trackingOptionID: ['TrackingOptionID', optional(string())],
});
