/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type3Enum
 */
export enum Type3Enum {
  ACCPAY = 'ACCPAY',
  ACCPAYCREDIT = 'ACCPAYCREDIT',
  APOVERPAYMENT = 'APOVERPAYMENT',
  APPREPAYMENT = 'APPREPAYMENT',
  ACCREC = 'ACCREC',
  ACCRECCREDIT = 'ACCRECCREDIT',
  AROVERPAYMENT = 'AROVERPAYMENT',
  ARPREPAYMENT = 'ARPREPAYMENT',
}

/**
 * Schema for Type3Enum
 */
export const type3EnumSchema: Schema<Type3Enum> = stringEnum(Type3Enum);
