/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type4Enum
 */
export enum Type4Enum {
  ACCPAYCREDIT = 'ACCPAYCREDIT',
  ACCRECCREDIT = 'ACCRECCREDIT',
}

/**
 * Schema for Type4Enum
 */
export const type4EnumSchema: Schema<Type4Enum> = stringEnum(Type4Enum);
