/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type5Enum
 */
export enum Type5Enum {
  RECEIVE = 'RECEIVE',
  RECEIVEOVERPAYMENT = 'RECEIVE-OVERPAYMENT',
  RECEIVEPREPAYMENT = 'RECEIVE-PREPAYMENT',
  SPEND = 'SPEND',
  SPENDOVERPAYMENT = 'SPEND-OVERPAYMENT',
  SPENDPREPAYMENT = 'SPEND-PREPAYMENT',
  RECEIVETRANSFER = 'RECEIVE-TRANSFER',
  SPENDTRANSFER = 'SPEND-TRANSFER',
}

/**
 * Schema for Type5Enum
 */
export const type5EnumSchema: Schema<Type5Enum> = stringEnum(Type5Enum);
