/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type2Enum
 */
export enum Type2Enum {
  RECEIVEPREPAYMENT = 'RECEIVE-PREPAYMENT',
  SPENDPREPAYMENT = 'SPEND-PREPAYMENT',
  ARPREPAYMENT = 'ARPREPAYMENT',
  APPREPAYMENT = 'APPREPAYMENT',
}

/**
 * Schema for Type2Enum
 */
export const type2EnumSchema: Schema<Type2Enum> = stringEnum(Type2Enum);
