/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type1Enum
 */
export enum Type1Enum {
  RECEIVEOVERPAYMENT = 'RECEIVE-OVERPAYMENT',
  SPENDOVERPAYMENT = 'SPEND-OVERPAYMENT',
  AROVERPAYMENT = 'AROVERPAYMENT',
}

/**
 * Schema for Type1Enum
 */
export const type1EnumSchema: Schema<Type1Enum> = stringEnum(Type1Enum);
