/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { User, userSchema } from './user.js';

export interface Users {
  users?: User[];
}

export const usersSchema: Schema<Users> = lazy(() =>
  object({ users: ['Users', optional(array(userSchema))] })
);
