/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema.js';
import {
  OrganisationRoleEnum,
  organisationRoleEnumSchema,
} from './organisationRoleEnum.js';

export interface User {
  /** Email address of user */
  emailAddress?: string;
  /** First name of user */
  firstName?: string;
  /** Boolean to indicate if user is the subscriber */
  isSubscriber?: boolean;
  /** Last name of user */
  lastName?: string;
  /** User role that defines permissions in Xero and via API (READONLY, INVOICEONLY, STANDARD, FINANCIALADVISER, etc) */
  organisationRole?: OrganisationRoleEnum;
  /** Timestamp of last change to user */
  updatedDateUTC?: string;
  /** Xero identifier */
  userID?: string;
}

export const userSchema: Schema<User> = object({
  emailAddress: ['EmailAddress', optional(string())],
  firstName: ['FirstName', optional(string())],
  isSubscriber: ['IsSubscriber', optional(boolean())],
  lastName: ['LastName', optional(string())],
  organisationRole: ['OrganisationRole', optional(organisationRoleEnumSchema)],
  updatedDateUTC: ['UpdatedDateUTC', optional(string())],
  userID: ['UserID', optional(string())],
});
