/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface ValidationError {
  /** Validation error message */
  message?: string;
}

export const validationErrorSchema: Schema<ValidationError> = object({
  message: ['Message', optional(string())],
});
