/**
 * Xero Accounting APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for VersionEnum
 */
export enum VersionEnum {
  AU = 'AU',
  NZ = 'NZ',
  GLOBAL = 'GLOBAL',
  UK = 'UK',
  US = 'US',
  AUONRAMP = 'AUONRAMP',
  NZONRAMP = 'NZONRAMP',
  GLOBALONRAMP = 'GLOBALONRAMP',
  UKONRAMP = 'UKONRAMP',
  USONRAMP = 'USONRAMP',
}

/**
 * Schema for VersionEnum
 */
export const versionEnumSchema: Schema<VersionEnum> = stringEnum(VersionEnum);
